/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddProduct.java
 *
 * Created on 06-Oct-2012, 10:21:08
 */

package TgsSystem;

import java.sql.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowEvent;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author Babathurpe
 */
public class AddProduct extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /** Creates new form AddProduct */
    public AddProduct() {
        initComponents();
    }

     public void close(){
             WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
             Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        DeleteShedBtn = new javax.swing.JButton();
        UpdateShedBtn = new javax.swing.JButton();
        ShedTypeTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ShedPriceTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        AddShedBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        ShedImgBtn = new javax.swing.JButton();
        ShedImgTxt = new javax.swing.JTextField();
        ShedNameTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        LogOutBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        DeleteExtraBtn = new javax.swing.JButton();
        UpdateExtraBtn = new javax.swing.JButton();
        AddExtraBtn = new javax.swing.JButton();
        ExtraTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ExtraPriceTxt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        DeleteRoofBtn = new javax.swing.JButton();
        UpdateRoofBtn = new javax.swing.JButton();
        AddRoofBtn = new javax.swing.JButton();
        RooftypeTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        RoofPriceTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manager :: Add Product");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Modern No. 20", 1, 24));
        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setText("TIMBERLAND GARDEN SHEDS ADMIN - ADD PRODUCTS .");
        jLabel7.setName("jLabel7"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2), "Add Product", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Palatino Linotype", 1, 14), new java.awt.Color(153, 0, 51))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        DeleteShedBtn.setText("Delete Shed");
        DeleteShedBtn.setName("DeleteShedBtn"); // NOI18N
        DeleteShedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteShedBtnActionPerformed(evt);
            }
        });

        UpdateShedBtn.setText("Update Shed");
        UpdateShedBtn.setName("UpdateShedBtn"); // NOI18N
        UpdateShedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateShedBtnActionPerformed(evt);
            }
        });

        ShedTypeTxt.setName("ShedTypeTxt"); // NOI18N

        jLabel3.setText("Shed Price:");
        jLabel3.setName("jLabel3"); // NOI18N

        ShedPriceTxt.setName("ShedPriceTxt"); // NOI18N

        jLabel1.setText("Shed Type:");
        jLabel1.setName("jLabel1"); // NOI18N

        AddShedBtn.setText("Add Shed");
        AddShedBtn.setName("AddShedBtn"); // NOI18N
        AddShedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddShedBtnActionPerformed(evt);
            }
        });

        jLabel8.setText("Shed Picture:");
        jLabel8.setName("jLabel8"); // NOI18N

        ShedImgBtn.setText("Add Image");
        ShedImgBtn.setName("ShedImgBtn"); // NOI18N
        ShedImgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShedImgBtnActionPerformed(evt);
            }
        });

        ShedImgTxt.setName("ShedImgTxt"); // NOI18N

        ShedNameTxt.setName("ShedNameTxt"); // NOI18N

        jLabel2.setText("Shed Name:");
        jLabel2.setName("jLabel2"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ShedTypeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(AddShedBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeleteShedBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdateShedBtn)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ShedNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(55, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ShedImgTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ShedImgBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ShedPriceTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                .addGap(45, 45, 45)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ShedTypeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ShedNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ShedPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ShedImgBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ShedImgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddShedBtn)
                    .addComponent(DeleteShedBtn)
                    .addComponent(UpdateShedBtn))
                .addContainerGap())
        );

        LogOutBtn.setFont(new java.awt.Font("Tahoma", 1, 11));
        LogOutBtn.setText("Log Out");
        LogOutBtn.setName("LogOutBtn"); // NOI18N
        LogOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBtnActionPerformed(evt);
            }
        });

        BackBtn.setFont(new java.awt.Font("Tahoma", 1, 11));
        BackBtn.setText("Back");
        BackBtn.setName("BackBtn"); // NOI18N
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2), "Add Extras", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Palatino Linotype", 1, 14), new java.awt.Color(153, 0, 51))); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N

        DeleteExtraBtn.setText("Delete Extras");
        DeleteExtraBtn.setName("DeleteExtraBtn"); // NOI18N
        DeleteExtraBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteExtraBtnActionPerformed(evt);
            }
        });

        UpdateExtraBtn.setText("Update Extras");
        UpdateExtraBtn.setName("UpdateExtraBtn"); // NOI18N
        UpdateExtraBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateExtraBtnActionPerformed(evt);
            }
        });

        AddExtraBtn.setText("Add Extras");
        AddExtraBtn.setName("AddExtraBtn"); // NOI18N
        AddExtraBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddExtraBtnActionPerformed(evt);
            }
        });

        ExtraTxt.setName("ExtraTxt"); // NOI18N

        jLabel4.setText("Product Extras:");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText("Extras Price:");
        jLabel5.setName("jLabel5"); // NOI18N

        ExtraPriceTxt.setName("ExtraPriceTxt"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ExtraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(ExtraPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AddExtraBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeleteExtraBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdateExtraBtn)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ExtraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ExtraPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddExtraBtn)
                    .addComponent(DeleteExtraBtn)
                    .addComponent(UpdateExtraBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2), "Add Roof", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Palatino Linotype", 1, 14), new java.awt.Color(153, 0, 51))); // NOI18N
        jPanel3.setName("jPanel3"); // NOI18N

        DeleteRoofBtn.setText("Delete Roof");
        DeleteRoofBtn.setName("DeleteRoofBtn"); // NOI18N
        DeleteRoofBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteRoofBtnActionPerformed(evt);
            }
        });

        UpdateRoofBtn.setText("Update Roof");
        UpdateRoofBtn.setName("UpdateRoofBtn"); // NOI18N
        UpdateRoofBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateRoofBtnActionPerformed(evt);
            }
        });

        AddRoofBtn.setText("Add Roof");
        AddRoofBtn.setName("AddRoofBtn"); // NOI18N
        AddRoofBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRoofBtnActionPerformed(evt);
            }
        });

        RooftypeTxt.setName("RooftypeTxt"); // NOI18N

        jLabel6.setText("Rooftype:");
        jLabel6.setName("jLabel6"); // NOI18N

        RoofPriceTxt.setName("RoofPriceTxt"); // NOI18N

        jLabel9.setText("Roof Price:");
        jLabel9.setName("jLabel9"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(AddRoofBtn)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteRoofBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdateRoofBtn))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(RoofPriceTxt))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(RooftypeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(RooftypeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(RoofPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateRoofBtn)
                    .addComponent(DeleteRoofBtn)
                    .addComponent(AddRoofBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(298, Short.MAX_VALUE)
                .addComponent(BackBtn)
                .addGap(26, 26, 26)
                .addComponent(LogOutBtn)
                .addGap(266, 266, 266))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackBtn)
                    .addComponent(LogOutBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBtnActionPerformed
        // TODO add your handling code here:
        close();
        TgsMainFrame main = new TgsMainFrame();
        main.setVisible(true);
}//GEN-LAST:event_LogOutBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        close();
        AdminFrame home = new AdminFrame();
        home.setVisible(true);
}//GEN-LAST:event_BackBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        conn = mysqlconnect.ConnectDb();
    }//GEN-LAST:event_formWindowOpened

    public boolean ValidateShedType(){
        boolean check = false;
        String name = ShedTypeTxt.getText();
        if(name.length() == 0 || name == null){
            JOptionPane.showMessageDialog(null, "Shed Type cannot be empty.");
            ShedTypeTxt.requestFocusInWindow();
        } else{
            check = true;
        }
        return check;
      }
    public boolean ValidateShedName(){
        boolean check = false;
        String name = ShedNameTxt.getText();
        if(name.length() == 0 || name == null){
            JOptionPane.showMessageDialog(null, "Shed Name cannot be empty.");
            ShedNameTxt.requestFocusInWindow();
        } else{
            check = true;
        }
        return check;
      }
    public boolean ValidateShedPrice(){
        boolean check = false;
        String name = ShedPriceTxt.getText();
        if(name.length() == 0 || name == null){
            JOptionPane.showMessageDialog(null, "Shed Price cannot be empty.");
            ShedPriceTxt.requestFocusInWindow();
        } else{
            check = true;
        }
        return check;
      }

    private void AddShedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddShedBtnActionPerformed
        // TODO add your handling code here:
        if(ValidateShedType() && ValidateShedName() && ValidateShedPrice()){
        try{
        String sql = "insert into products (shedtype,shedname,shedprice,prodimage) values (?,?,?,?)";
        
            pst = conn.prepareStatement(sql);
            pst.setString(1, ShedTypeTxt.getText());
            pst.setString(2, ShedNameTxt.getText());
            pst.setString(3, ShedPriceTxt.getText());
            pst.setBytes(4, shedImage);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Shed Info has been added.");
            //clear text field and combo box to default null values after update.
            ShedTypeTxt.setText(null);
            ShedPriceTxt.setText(null);
            ShedImgTxt.setText(null);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Price has has to be a number.\nAdd an image."); //
        }
     }
}//GEN-LAST:event_AddShedBtnActionPerformed


    private void DeleteShedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteShedBtnActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(rootPane, "Are you sure?","Delete", JOptionPane.YES_NO_OPTION);
       if(confirm==0){
       String sql = "delete from products where shedname = ? ";
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1, ShedTypeTxt.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Shed Info has been deleted.");
            // clear text field and combo box to default null values after delete.
            ShedTypeTxt.setText(null);
            ShedPriceTxt.setText(null);
            ShedImgTxt.setText(null);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
       }
}//GEN-LAST:event_DeleteShedBtnActionPerformed

        private void UpdateShedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateShedBtnActionPerformed
        // TODO add your handling code here:
            if(ValidateShedType() && ValidateShedName() && ValidateShedPrice()){
        try{
            //get values from text fields to be edited.
            String Shedtype = ShedTypeTxt.getText();
            String ShedName = ShedNameTxt.getText();
            String ShedPrice = ShedPriceTxt.getText();
            //sql statement to be executed
            String sql = "update products set shedname = '"+ShedName+"', Shedtype = '"+Shedtype+"',productprice = '"+ShedPrice+"' where shedname = '"+ShedName+"' ";
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Shed Info has been updated.");
            //clear text field and combo box to default null values after update.
            ShedTypeTxt.setText(null);
            ShedPriceTxt.setText(null);
            ShedImgTxt.setText(null);
        } catch(Exception e){

        }
     }
}//GEN-LAST:event_UpdateShedBtnActionPerformed


        public boolean ValidateExtrasName(){
        boolean check = false;
        String name = ExtraTxt.getText();
        if(name.length() == 0 || name == null){
            JOptionPane.showMessageDialog(null, "Extra Name cannot be empty.");
            ExtraTxt.requestFocusInWindow();
        } else{
            check = true;
        }
        return check;
      }

        public boolean ValidateExtrasPrice(){
        boolean check = false;
        String name = ExtraPriceTxt.getText();
        if(name.length() == 0 || name == null){
            JOptionPane.showMessageDialog(null, "Extra Price cannot be empty.");
            ExtraPriceTxt.requestFocusInWindow();
        } else{
            check = true;
        }
        return check;
      }


    private void AddExtraBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddExtraBtnActionPerformed
        // TODO add your handling code here:
        if(ValidateExtrasName() && ValidateExtrasPrice()){
        String sql = "insert into extras (extraname,extraprice) values (?,?)";
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1, ExtraTxt.getText());
            pst.setString(2, ExtraPriceTxt.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Extras Info has been added.");
            //clear text field and combo box to default null values after update.
            ExtraTxt.setText(null);
            ExtraPriceTxt.setText(null);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "A similar Extras details already exists.\nPrice has to be a number.");
        }
      }
    }//GEN-LAST:event_AddExtraBtnActionPerformed

    private void DeleteExtraBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteExtraBtnActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(rootPane, "Are you sure?","Delete", JOptionPane.YES_NO_OPTION);
       if(confirm==0){
       String sql = "delete from extras where extraname = ? ";
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1, ExtraTxt.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Extras Info has been deleted.");
            // clear text field and combo box to default null values after delete.
            ExtraTxt.setText(null);
            ExtraPriceTxt.setText(null);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
       }
    }//GEN-LAST:event_DeleteExtraBtnActionPerformed

    private void UpdateExtraBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateExtraBtnActionPerformed
        // TODO add your handling code here:
        if(ValidateExtrasName() && ValidateExtrasPrice()){
        try{
            //get values from text fields to be edited.
            String ExtraName = ExtraTxt.getText();
            String ExtraPrice = ExtraPriceTxt.getText();
            //sql statement to be executed
            String sql = "update extras set extraname = '"+ExtraName+"',extraprice = '"+ExtraPrice+"' where extraname = '"+ExtraName+"' ";
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Extras Info and/or Price has been updated.");
            //clear text field and combo box to default null values after update.
            ExtraTxt.setText(null);
            ExtraPriceTxt.setText(null);
        } catch(Exception e){

        }
      }
    }//GEN-LAST:event_UpdateExtraBtnActionPerformed


     public boolean ValidateRoofPrice(){
        boolean check = false;
        String name = RoofPriceTxt.getText();
        if(name.length() == 0 || name == null){
            JOptionPane.showMessageDialog(null, "Roof Price cannot be empty.");
            RoofPriceTxt.requestFocusInWindow();
        } else{
            check = true;
        }
        return check;
      }

     public boolean ValidateRoofType(){
        boolean check = false;
        String name = RooftypeTxt.getText();
        if(name.length() == 0 || name == null){
            JOptionPane.showMessageDialog(null, "Roof Name cannot be empty.");
            RooftypeTxt.requestFocusInWindow();
        } else{
            check = true;
        }
        return check;
      }


    private void AddRoofBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRoofBtnActionPerformed
        // TODO add your handling code here:
        if(ValidateRoofType() && ValidateRoofPrice()){
        String sql = "insert into rooftype (rooftype,roofprice) values (?,?)";
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1, RooftypeTxt.getText());
            pst.setString(2, RoofPriceTxt.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Roof Type Info has been added.");
            //clear text field and combo box to default null values after update.
            RooftypeTxt.setText(null);
            RoofPriceTxt.setText(null);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Roof type details already exists.\nPRice has to be a number.");
        }
      }
    }//GEN-LAST:event_AddRoofBtnActionPerformed

    private void DeleteRoofBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRoofBtnActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(rootPane, "Are you sure?","Delete", JOptionPane.YES_NO_OPTION);
       if(confirm==0){
       String sql = "delete from rooftype where rooftype = ? ";
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1, RooftypeTxt.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Roof Type has been deleted.");
            // clear text field and combo box to default null values after delete.
            RooftypeTxt.setText(null);
            RoofPriceTxt.setText(null);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
       }
    }//GEN-LAST:event_DeleteRoofBtnActionPerformed

    private void UpdateRoofBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateRoofBtnActionPerformed
        // TODO add your handling code here:
        if(ValidateRoofType() && ValidateRoofPrice()){
        try{
            //get values from text fields to be edited.
            String RoofType = RooftypeTxt.getText();
            String RoofPrice = RoofPriceTxt.getText();
            
            //sql statement to be executed
            String sql = "update rooftype set rooftype = '"+RoofType+"',roofprice = '"+RoofPrice+"'";
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Roof Type and/or Price has been updated.");
            //clear text field and combo box to default null values after update.
            RooftypeTxt.setText(null);
            RoofPriceTxt.setText(null);
            
        } catch(Exception e){

        }
       }
    }//GEN-LAST:event_UpdateRoofBtnActionPerformed

    private void ShedImgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShedImgBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser chooseImgFile = new JFileChooser();
        FileNameExtensionFilter JPG = new FileNameExtensionFilter("JPEG", "jpg");
        chooseImgFile.addChoosableFileFilter(JPG);
        FileNameExtensionFilter GIF = new FileNameExtensionFilter("GIF", "gif");
        chooseImgFile.addChoosableFileFilter(GIF);
        FileNameExtensionFilter PNG = new FileNameExtensionFilter("PNG", "png");
        chooseImgFile.addChoosableFileFilter(PNG);
        //Disable the "All Files" option in the open dialog
        chooseImgFile.setAcceptAllFileFilterUsed(false);
        //Set Deafult file filter to jpeg.
        chooseImgFile.setFileFilter(JPG);
        chooseImgFile.showOpenDialog(null);
        File img = chooseImgFile.getSelectedFile();
         imgPath = img.getAbsolutePath();
        ShedImgTxt.setText(imgPath);
        try{
            File image = new File(imgPath);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for(int readNum; (readNum=fis.read(buf))!=-1;){
                bos.write(buf, 0, readNum);
            }
            shedImage = bos.toByteArray();
        } catch(Exception e){

        }

    }//GEN-LAST:event_ShedImgBtnActionPerformed

   
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddExtraBtn;
    private javax.swing.JButton AddRoofBtn;
    private javax.swing.JButton AddShedBtn;
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton DeleteExtraBtn;
    private javax.swing.JButton DeleteRoofBtn;
    private javax.swing.JButton DeleteShedBtn;
    private javax.swing.JTextField ExtraPriceTxt;
    private javax.swing.JTextField ExtraTxt;
    private javax.swing.JButton LogOutBtn;
    private javax.swing.JTextField RoofPriceTxt;
    private javax.swing.JTextField RooftypeTxt;
    private javax.swing.JButton ShedImgBtn;
    private javax.swing.JTextField ShedImgTxt;
    private javax.swing.JTextField ShedNameTxt;
    private javax.swing.JTextField ShedPriceTxt;
    private javax.swing.JTextField ShedTypeTxt;
    private javax.swing.JButton UpdateExtraBtn;
    private javax.swing.JButton UpdateRoofBtn;
    private javax.swing.JButton UpdateShedBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    private ImageIcon format = null;
    String imgPath = null;
    int s = 0;
    byte[] shedImage = null;
}
