/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdminOrderForm.java
 *
 * Created on 30-Sep-2012, 09:41:35
 */

package TgsSystem;

import java.sql.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowEvent;
import java.text.DecimalFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
/**
 *
 * @author Babathurpe
 */
public class AdminOrderForm extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    /** Creates new form AdminOrderForm */
    public AdminOrderForm() {
        initComponents();
    }

     public void close(){
             WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
             Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleGrpRdBtn = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        ErrorLabel = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        CustOrderScrollPane = new javax.swing.JScrollPane();
        CustOrderPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        OrderNoTxt = new javax.swing.JTextField();
        SurnameTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        AddressTxt = new javax.swing.JTextField();
        shipAddress1Txt = new javax.swing.JTextField();
        shipAdd1Lbl = new javax.swing.JLabel();
        TownTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        PostcodeTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Emailtxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        QtyTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        FirstnameTxt = new javax.swing.JTextField();
        RdBtnMr = new javax.swing.JRadioButton();
        RdBtnMrs = new javax.swing.JRadioButton();
        RdBtnMiss = new javax.swing.JRadioButton();
        RdBtnSir = new javax.swing.JRadioButton();
        RdBtnMa = new javax.swing.JRadioButton();
        RdBtnDr = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        UnitPriceTxt = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        subtotalTxt = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        ComboShedType = new javax.swing.JComboBox();
        ComboShedName = new javax.swing.JComboBox();
        ComboRoofType = new javax.swing.JComboBox();
        ComboExtras = new javax.swing.JComboBox();
        SaveBtn = new javax.swing.JButton();
        ResetBtn = new javax.swing.JButton();
        DepositTxt = new javax.swing.JTextField();
        surnameErr = new javax.swing.JLabel();
        AddErr = new javax.swing.JLabel();
        TownErr = new javax.swing.JLabel();
        Add1Err = new javax.swing.JLabel();
        PostcodeErr = new javax.swing.JLabel();
        phoneErr = new javax.swing.JLabel();
        qtyErr = new javax.swing.JLabel();
        titleErr = new javax.swing.JLabel();
        Address1Txt = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        shipAddressTxt = new javax.swing.JTextField();
        shipAddLbl = new javax.swing.JLabel();
        shipAddCheck = new javax.swing.JCheckBox();
        shipAdd1Err = new javax.swing.JLabel();
        shipAddErr = new javax.swing.JLabel();
        emailErr = new javax.swing.JLabel();
        firstnameErr = new javax.swing.JLabel();
        imgBox = new javax.swing.JDesktopPane();
        ImageBox = new javax.swing.JLabel();
        extraPriceTxt = new javax.swing.JTextField();
        roofPriceTxt = new javax.swing.JTextField();
        shedPriceTxt = new javax.swing.JTextField();
        PhoneTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        LogOutBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manager :: Customer Order Form");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("CUSTOMER ORDER FORM.");
        jLabel1.setName("jLabel1"); // NOI18N

        ErrorLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ErrorLabel.setForeground(new java.awt.Color(204, 0, 0));
        ErrorLabel.setText("Please Fill in the fields marked ***");
        ErrorLabel.setName("ErrorLabel"); // NOI18N

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 0, 0));
        jLabel21.setText("** All fields are required. **");
        jLabel21.setName("jLabel21"); // NOI18N

        CustOrderScrollPane.setName("CustOrderScrollPane"); // NOI18N

        CustOrderPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CustOrderPanel.setMaximumSize(new java.awt.Dimension(327, 350));
        CustOrderPanel.setName("CustOrderPanel"); // NOI18N
        CustOrderPanel.setPreferredSize(new java.awt.Dimension(500, 680));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Order Number:");
        jLabel2.setName("jLabel2"); // NOI18N

        OrderNoTxt.setEditable(false);
        OrderNoTxt.setName("OrderNoTxt"); // NOI18N

        SurnameTxt.setName("SurnameTxt"); // NOI18N
        SurnameTxt.setNextFocusableComponent(FirstnameTxt);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Surname:");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Address 1:");
        jLabel5.setName("jLabel5"); // NOI18N

        AddressTxt.setName("AddressTxt"); // NOI18N
        AddressTxt.setNextFocusableComponent(Address1Txt);

        shipAddress1Txt.setName("shipAddress1Txt"); // NOI18N
        shipAddress1Txt.setNextFocusableComponent(TownTxt);

        shipAdd1Lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        shipAdd1Lbl.setText("Ship to Address 2:");
        shipAdd1Lbl.setName("shipAdd1Lbl"); // NOI18N

        TownTxt.setName("TownTxt"); // NOI18N
        TownTxt.setNextFocusableComponent(PostcodeTxt);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Town:");
        jLabel7.setName("jLabel7"); // NOI18N

        PostcodeTxt.setName("PostcodeTxt"); // NOI18N
        PostcodeTxt.setNextFocusableComponent(PhoneTxt);
        PostcodeTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                PostcodeTxtFocusLost(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Postcode:");
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Telephone:");
        jLabel9.setName("jLabel9"); // NOI18N

        Emailtxt.setName("Emailtxt"); // NOI18N
        Emailtxt.setNextFocusableComponent(ComboShedType);
        Emailtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                EmailtxtFocusLost(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Email:");
        jLabel10.setName("jLabel10"); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Shed Type:");
        jLabel11.setName("jLabel11"); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Shed Name:");
        jLabel12.setName("jLabel12"); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Roof Type:");
        jLabel14.setName("jLabel14"); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Extras:");
        jLabel15.setName("jLabel15"); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Quantity:");
        jLabel16.setName("jLabel16"); // NOI18N

        QtyTxt.setName("QtyTxt"); // NOI18N
        QtyTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                QtyTxtKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Firstname:");
        jLabel4.setName("jLabel4"); // NOI18N

        FirstnameTxt.setName("FirstnameTxt"); // NOI18N
        FirstnameTxt.setNextFocusableComponent(AddressTxt);

        titleGrpRdBtn.add(RdBtnMr);
        RdBtnMr.setText("Mr");
        RdBtnMr.setName("RdBtnMr"); // NOI18N
        RdBtnMr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdBtnMrActionPerformed(evt);
            }
        });

        titleGrpRdBtn.add(RdBtnMrs);
        RdBtnMrs.setText("Mrs");
        RdBtnMrs.setName("RdBtnMrs"); // NOI18N
        RdBtnMrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdBtnMrsActionPerformed(evt);
            }
        });

        titleGrpRdBtn.add(RdBtnMiss);
        RdBtnMiss.setText("Miss");
        RdBtnMiss.setName("RdBtnMiss"); // NOI18N
        RdBtnMiss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdBtnMissActionPerformed(evt);
            }
        });

        titleGrpRdBtn.add(RdBtnSir);
        RdBtnSir.setText("Sir");
        RdBtnSir.setName("RdBtnSir"); // NOI18N
        RdBtnSir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdBtnSirActionPerformed(evt);
            }
        });

        titleGrpRdBtn.add(RdBtnMa);
        RdBtnMa.setText("Ma");
        RdBtnMa.setName("RdBtnMa"); // NOI18N
        RdBtnMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdBtnMaActionPerformed(evt);
            }
        });

        titleGrpRdBtn.add(RdBtnDr);
        RdBtnDr.setText("Dr");
        RdBtnDr.setName("RdBtnDr"); // NOI18N
        RdBtnDr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdBtnDrActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 0, 51));
        jLabel17.setText("Customer Details");
        jLabel17.setName("jLabel17"); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Unit Price:");
        jLabel18.setName("jLabel18"); // NOI18N

        UnitPriceTxt.setEditable(false);
        UnitPriceTxt.setName("UnitPriceTxt"); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Deposit:");
        jLabel19.setName("jLabel19"); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Subtotal:");
        jLabel20.setName("jLabel20"); // NOI18N

        subtotalTxt.setEditable(false);
        subtotalTxt.setName("subtotalTxt"); // NOI18N

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 0, 51));
        jLabel24.setText("Product Details");
        jLabel24.setName("jLabel24"); // NOI18N

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setText("Title:");
        jLabel25.setName("jLabel25"); // NOI18N

        ComboShedType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Shed type" }));
        ComboShedType.setName("ComboShedType"); // NOI18N
        ComboShedType.setNextFocusableComponent(ComboShedName);

        ComboShedName.setMaximumRowCount(20);
        ComboShedName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Shed Name" }));
        ComboShedName.setName("ComboShedName"); // NOI18N
        ComboShedName.setNextFocusableComponent(ComboRoofType);
        ComboShedName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboShedNameActionPerformed(evt);
            }
        });

        ComboRoofType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Roof Type" }));
        ComboRoofType.setName("ComboRoofType"); // NOI18N
        ComboRoofType.setNextFocusableComponent(ComboExtras);
        ComboRoofType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboRoofTypeActionPerformed(evt);
            }
        });

        ComboExtras.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Extras" }));
        ComboExtras.setName("ComboExtras"); // NOI18N
        ComboExtras.setNextFocusableComponent(QtyTxt);
        ComboExtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboExtrasActionPerformed(evt);
            }
        });

        SaveBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SaveBtn.setForeground(new java.awt.Color(102, 0, 102));
        SaveBtn.setText("Save & Send to TGS HQ");
        SaveBtn.setName("SaveBtn"); // NOI18N
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        ResetBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ResetBtn.setForeground(new java.awt.Color(102, 0, 102));
        ResetBtn.setText("Reset All Fields");
        ResetBtn.setName("ResetBtn"); // NOI18N
        ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtnActionPerformed(evt);
            }
        });

        DepositTxt.setEditable(false);
        DepositTxt.setName("DepositTxt"); // NOI18N

        surnameErr.setForeground(new java.awt.Color(204, 0, 0));
        surnameErr.setText("***");
        surnameErr.setName("surnameErr"); // NOI18N

        AddErr.setForeground(new java.awt.Color(204, 0, 0));
        AddErr.setText("***");
        AddErr.setName("AddErr"); // NOI18N

        TownErr.setForeground(new java.awt.Color(204, 0, 0));
        TownErr.setText("***");
        TownErr.setName("TownErr"); // NOI18N

        Add1Err.setForeground(new java.awt.Color(204, 0, 0));
        Add1Err.setText("***");
        Add1Err.setName("Add1Err"); // NOI18N

        PostcodeErr.setForeground(new java.awt.Color(204, 0, 0));
        PostcodeErr.setText("***");
        PostcodeErr.setName("PostcodeErr"); // NOI18N

        phoneErr.setForeground(new java.awt.Color(204, 0, 0));
        phoneErr.setText("***");
        phoneErr.setName("phoneErr"); // NOI18N

        qtyErr.setForeground(new java.awt.Color(204, 0, 0));
        qtyErr.setText("***");
        qtyErr.setName("qtyErr"); // NOI18N

        titleErr.setForeground(new java.awt.Color(204, 0, 0));
        titleErr.setText("***");
        titleErr.setName("titleErr"); // NOI18N

        Address1Txt.setName("Address1Txt"); // NOI18N
        Address1Txt.setNextFocusableComponent(shipAddCheck);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setText("Address 2:");
        jLabel26.setName("jLabel26"); // NOI18N

        shipAddressTxt.setName("shipAddressTxt"); // NOI18N
        shipAddressTxt.setNextFocusableComponent(shipAddress1Txt);

        shipAddLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        shipAddLbl.setText("Ship to Address 1:");
        shipAddLbl.setName("shipAddLbl"); // NOI18N

        shipAddCheck.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        shipAddCheck.setForeground(new java.awt.Color(204, 0, 0));
        shipAddCheck.setText("Ship To Different Address?");
        shipAddCheck.setName("shipAddCheck"); // NOI18N
        shipAddCheck.setNextFocusableComponent(shipAddressTxt);
        shipAddCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shipAddCheckActionPerformed(evt);
            }
        });

        shipAdd1Err.setForeground(new java.awt.Color(204, 0, 0));
        shipAdd1Err.setText("***");
        shipAdd1Err.setName("shipAdd1Err"); // NOI18N

        shipAddErr.setForeground(new java.awt.Color(204, 0, 0));
        shipAddErr.setText("***");
        shipAddErr.setName("shipAddErr"); // NOI18N

        emailErr.setForeground(new java.awt.Color(204, 0, 0));
        emailErr.setText("***");
        emailErr.setName("emailErr"); // NOI18N

        firstnameErr.setForeground(new java.awt.Color(204, 0, 0));
        firstnameErr.setText("***");
        firstnameErr.setName("firstnameErr"); // NOI18N

        imgBox.setName("imgBox"); // NOI18N
        imgBox.setLayout(null);

        ImageBox.setName("ImageBox"); // NOI18N
        imgBox.add(ImageBox);
        ImageBox.setBounds(10, 10, 200, 180);

        extraPriceTxt.setEditable(false);
        extraPriceTxt.setName("extraPriceTxt"); // NOI18N

        roofPriceTxt.setEditable(false);
        roofPriceTxt.setName("roofPriceTxt"); // NOI18N

        shedPriceTxt.setEditable(false);
        shedPriceTxt.setName("shedPriceTxt"); // NOI18N

        PhoneTxt.setName("PhoneTxt"); // NOI18N
        PhoneTxt.setNextFocusableComponent(PostcodeTxt);
        PhoneTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                PhoneTxtFocusLost(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("XXX-XXXXXXX");
        jLabel6.setName("jLabel6"); // NOI18N

        javax.swing.GroupLayout CustOrderPanelLayout = new javax.swing.GroupLayout(CustOrderPanel);
        CustOrderPanel.setLayout(CustOrderPanelLayout);
        CustOrderPanelLayout.setHorizontalGroup(
            CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustOrderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CustOrderPanelLayout.createSequentialGroup()
                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addGroup(CustOrderPanelLayout.createSequentialGroup()
                                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel14))
                                .addGap(25, 25, 25)
                                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CustOrderPanelLayout.createSequentialGroup()
                                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ComboShedType, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ComboShedName, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(shedPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20))
                                    .addGroup(CustOrderPanelLayout.createSequentialGroup()
                                        .addComponent(ComboRoofType, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(extraPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(roofPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(imgBox, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CustOrderPanelLayout.createSequentialGroup()
                                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26))
                                .addGap(46, 46, 46)
                                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CustOrderPanelLayout.createSequentialGroup()
                                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CustOrderPanelLayout.createSequentialGroup()
                                                .addComponent(SurnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(surnameErr))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CustOrderPanelLayout.createSequentialGroup()
                                                .addComponent(RdBtnMr)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(RdBtnMrs)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(RdBtnMiss)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(RdBtnSir)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(RdBtnMa)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RdBtnDr)
                                        .addGap(2, 2, 2)
                                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(titleErr)
                                            .addGroup(CustOrderPanelLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel4)
                                                .addGap(10, 10, 10)
                                                .addComponent(FirstnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Address1Txt, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(AddressTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Add1Err)
                                        .addComponent(AddErr))
                                    .addComponent(firstnameErr)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustOrderPanelLayout.createSequentialGroup()
                                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(shipAddLbl)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CustOrderPanelLayout.createSequentialGroup()
                                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TownTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TownErr)
                                            .addComponent(jLabel6))
                                        .addGap(4, 4, 4)
                                        .addComponent(phoneErr)
                                        .addGap(18, 18, 18)
                                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel10))
                                        .addGap(7, 7, 7)
                                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(PostcodeTxt)
                                            .addComponent(Emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(shipAddress1Txt)
                                    .addComponent(shipAddressTxt))
                                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CustOrderPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(emailErr, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PostcodeErr, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(shipAdd1Err)
                                        .addComponent(shipAddErr)))))
                        .addGap(991, 991, 991))
                    .addGroup(CustOrderPanelLayout.createSequentialGroup()
                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(CustOrderPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(OrderNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(shipAdd1Lbl)
                            .addGroup(CustOrderPanelLayout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(shipAddCheck)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(CustOrderPanelLayout.createSequentialGroup()
                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CustOrderPanelLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(SaveBtn)
                        .addGap(18, 18, 18)
                        .addComponent(ResetBtn))
                    .addGroup(CustOrderPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CustOrderPanelLayout.createSequentialGroup()
                                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15))
                                .addGap(34, 34, 34)
                                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ComboExtras, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(CustOrderPanelLayout.createSequentialGroup()
                                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(UnitPriceTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(QtyTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(qtyErr))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CustOrderPanelLayout.createSequentialGroup()
                                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel19))
                                .addGap(40, 40, 40)
                                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DepositTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(subtotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CustOrderPanelLayout.setVerticalGroup(
            CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustOrderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CustOrderPanelLayout.createSequentialGroup()
                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(OrderNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)
                        .addGap(13, 13, 13)
                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RdBtnMr)
                            .addComponent(RdBtnMrs)
                            .addComponent(RdBtnMiss)
                            .addComponent(RdBtnSir)
                            .addComponent(RdBtnMa)
                            .addComponent(RdBtnDr)
                            .addComponent(jLabel25)
                            .addComponent(titleErr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SurnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(surnameErr))
                            .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(FirstnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(firstnameErr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(AddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddErr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(Address1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add1Err))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shipAddCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shipAddLbl)
                    .addComponent(shipAddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shipAddErr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shipAdd1Lbl)
                    .addComponent(shipAddress1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shipAdd1Err))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CustOrderPanelLayout.createSequentialGroup()
                        .addComponent(TownTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6)
                            .addComponent(phoneErr)))
                    .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TownErr)
                        .addComponent(jLabel7))
                    .addGroup(CustOrderPanelLayout.createSequentialGroup()
                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(PostcodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PostcodeErr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emailErr))
                            .addComponent(jLabel10))))
                .addGap(26, 26, 26)
                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CustOrderPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CustOrderPanelLayout.createSequentialGroup()
                                .addComponent(ComboShedType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ComboShedName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(shedPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ComboRoofType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addComponent(roofPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(CustOrderPanelLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel11)
                                .addGap(14, 14, 14)
                                .addComponent(jLabel12)))
                        .addGap(11, 11, 11)
                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboExtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(extraPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(QtyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(qtyErr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UnitPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DepositTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subtotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)))
                    .addGroup(CustOrderPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(imgBox, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveBtn)
                    .addComponent(ResetBtn))
                .addGap(75, 75, 75))
        );

        CustOrderScrollPane.setViewportView(CustOrderPanel);

        LogOutBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LogOutBtn.setText("Log Out");
        LogOutBtn.setName("LogOutBtn"); // NOI18N
        LogOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBtnActionPerformed(evt);
            }
        });

        BackBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.setName("BackBtn"); // NOI18N
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(271, 271, 271)
                                .addComponent(BackBtn)
                                .addGap(58, 58, 58)
                                .addComponent(LogOutBtn)))
                        .addGap(0, 317, Short.MAX_VALUE))
                    .addComponent(CustOrderScrollPane))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ErrorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CustOrderScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackBtn)
                    .addComponent(LogOutBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBtnActionPerformed
        // TODO add your handling code here:
        close();
        TgsMainFrame main = new TgsMainFrame();
        main.setVisible(true);
}//GEN-LAST:event_LogOutBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        close();
        AdminFrame home = new AdminFrame();
        home.setVisible(true);
}//GEN-LAST:event_BackBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        int orderNo = (int)(Math.round(Math.random() * 100000));
        String order = String.valueOf(orderNo);
        OrderNoTxt.setText(order);
        conn = mysqlconnect.ConnectDb();
        ErrorLabel.setVisible(false);
        Add1Err.setVisible(false);
        AddErr.setVisible(false);
        shipAddErr.setVisible(false);
        shipAdd1Err.setVisible(false);
        PostcodeErr.setVisible(false);
        TownErr.setVisible(false);
        emailErr.setVisible(false);
        firstnameErr.setVisible(false);
        phoneErr.setVisible(false);
        qtyErr.setVisible(false);
        surnameErr.setVisible(false);
        titleErr.setVisible(false);
        shipAddLbl.setVisible(false);
        shipAdd1Lbl.setVisible(false);
        shipAddressTxt.setVisible(false);
        shipAddress1Txt.setVisible(false);
        //Get the Shedtype from the database.
        String sqlShedType = "select shedtype from shedtype";
        try{
            pst=conn.prepareStatement(sqlShedType);
            rs = pst.executeQuery();
            while(rs.next()){
                String shedtype = rs.getString("shedtype");
                ComboShedType.addItem(shedtype);
                }
        } catch(Exception e){

        }
        //Get Shed Name from the Database
        String sqlShedname = "select shedname from products ";
        try{
            pst=conn.prepareStatement(sqlShedname);
            rs = pst.executeQuery();
            while(rs.next()){
                String shedname = rs.getString("shedname");
                ComboShedName.addItem(shedname);
                }
        } catch(Exception e){

        }

         //Get Roof Type from the Database
         String sqlRoofType = "select rooftype from rooftype";
        try{
            pst=conn.prepareStatement(sqlRoofType);
            rs = pst.executeQuery();
            while(rs.next()){
                String rooftype = rs.getString("rooftype");
                ComboRoofType.addItem(rooftype);
                }
        } catch(Exception e){

        }
         //Get Extras from the database
         String sqlExtras = "select extraname from extras";
        try{
            pst=conn.prepareStatement(sqlExtras);
            rs = pst.executeQuery();
            while(rs.next()){
                String extras = rs.getString("extraname");
                ComboExtras.addItem(extras);
                }
        } catch(Exception e){

        }
    }//GEN-LAST:event_formWindowOpened

    private void shipAddCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shipAddCheckActionPerformed
        // TODO add your handling code here:
        if(shipAddCheck.isSelected() == true){
            shipAddressTxt.setVisible(true);
            shipAddress1Txt.setVisible(true);
            shipAddLbl.setVisible(true);
            shipAdd1Lbl.setVisible(true);
        } else{
            shipAddressTxt.setVisible(false);
            shipAddress1Txt.setVisible(false);
            shipAddLbl.setVisible(false);
            shipAdd1Lbl.setVisible(false);
        }
}//GEN-LAST:event_shipAddCheckActionPerformed

    private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtnActionPerformed
        // TODO add your handling code here:
        titleGrpRdBtn.clearSelection();
        AddressTxt.setText(null);
        Address1Txt.setText(null);
        ComboExtras.setSelectedIndex(0);
        ComboShedName.setSelectedIndex(0);
        ComboRoofType.setSelectedIndex(0);
        ComboShedType.setSelectedIndex(0);
        DepositTxt.setText(null);
        Emailtxt.setText(null);
        FirstnameTxt.setText(null);
        OrderNoTxt.setText(null);
        PhoneTxt.setText(null);
        PostcodeTxt.setText(null);
        QtyTxt.setText(null);
        SurnameTxt.setText(null);
        TownTxt.setText(null);
        UnitPriceTxt.setText(null);
        shipAddress1Txt.setText(null);
        shipAddressTxt.setText(null);
        subtotalTxt.setText(null);
}//GEN-LAST:event_ResetBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
         if(ValidateSurname() && ValidateFirstname() && ValidateAddress() && ValidateAddress1() && ValidateTown() && ValidatePostcode()
                 && ValidatePhone() && ValidateEmail() && ValidateShedType() && ValidateShedName() && ValidateRooftype() && ValidateExtras()
                 && ValidateQty()){
        // Fields have been checked not to be empty. Therefore the information can be iserted into the database.
        String sql = "insert into tgscustomerform (orderid,Title,Firstname,Surname,Address, Address1,shipadd, shipadd1,Town,Postcode,Phone,email,shedtype,shedname,rooftype,extras,quantity,unitprice,deposit,subtotal) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        try{            
            pst = conn.prepareStatement(sql);
            pst.setString(1, OrderNoTxt.getText());
            pst.setString(2, title);
            pst.setString(3, FirstnameTxt.getText());
            pst.setString(4, SurnameTxt.getText());
            pst.setString(5, AddressTxt.getText());
            pst.setString(6, Address1Txt.getText());
            pst.setString(7, shipAddressTxt.getText());
            pst.setString(8, shipAddress1Txt.getText());
            pst.setString(9, TownTxt.getText());
            pst.setString(10, PostcodeTxt.getText());
            pst.setString(11, PhoneTxt.getText());
            pst.setString(12, Emailtxt.getText());
            String shedType = ComboShedType.getSelectedItem().toString();
            pst.setString(13, shedType);
            String prodName = ComboShedName.getSelectedItem().toString();
            pst.setString(14, prodName);
            String roofType = ComboRoofType.getSelectedItem().toString();
            pst.setString(15, roofType);
            String extras = ComboExtras.getSelectedItem().toString();
            pst.setString(16, extras);
            pst.setString(17, QtyTxt.getText());
            pst.setString(18, UnitPriceTxt.getText());
            pst.setString(19, DepositTxt.getText());
            pst.setString(20, subtotalTxt.getText());
            pst.execute();

            JOptionPane.showMessageDialog(null, "Order has been submitted. Thank You.");
            close();
            AdminFrame home = new AdminFrame();
            home.setVisible(true);

        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Please check for the following errors:\nSelect a title.\nQty cannot be empty.");
            //
        }

         }
        
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void RdBtnDrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdBtnDrActionPerformed
        // TODO add your handling code here:
        title = "Dr";
}//GEN-LAST:event_RdBtnDrActionPerformed

    private void RdBtnMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdBtnMaActionPerformed
        // TODO add your handling code here:
        title = "Ma";
}//GEN-LAST:event_RdBtnMaActionPerformed

    private void RdBtnSirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdBtnSirActionPerformed
        // TODO add your handling code here:
        title = "Sir";
}//GEN-LAST:event_RdBtnSirActionPerformed

    private void RdBtnMissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdBtnMissActionPerformed
        // TODO add your handling code here:
        title = "Miss";
}//GEN-LAST:event_RdBtnMissActionPerformed

    private void RdBtnMrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdBtnMrsActionPerformed
        // TODO add your handling code here:
        title = "Mrs";
}//GEN-LAST:event_RdBtnMrsActionPerformed

    private void RdBtnMrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdBtnMrActionPerformed
        // TODO add your handling code here:
        title = "Mr";
}//GEN-LAST:event_RdBtnMrActionPerformed

    private void ComboShedNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboShedNameActionPerformed
        // On select of item, get price and set shed name textfield to that price
        String shedname = ComboShedName.getSelectedItem().toString();
        try{
            String sql = "select prodimage,shedprice from products where shedname = '"+shedname+"'";
            pst = conn.prepareStatement(sql);
            //pst.setString(1, shedname);
            rs = pst.executeQuery();
            if(rs.next()){
               byte[] imagedata = rs.getBytes("prodimage");
               image = new ImageIcon(imagedata);
               ImageBox.setIcon(image);
               String setPrice = rs.getString("shedprice");
               shedPriceTxt.setText(setPrice);
            }

        } catch(Exception e){

        }
        
    }//GEN-LAST:event_ComboShedNameActionPerformed
        //RoundUp Values for unit price Amount
    public static double Round(double Rval, int Rpl) {
        double p = (double)Math.pow(10,Rpl);
        Rval = Rval * p;
        double tmp = Math.round(Rval);
        return (double)tmp/p;
  }
        //RoundUp Values for Subtotal Amount
     public static double Round1(double Rval, int Rpl) {
        double p = (double)Math.pow(10,Rpl);
        Rval = Rval * p;
        double tmp = Math.round(Rval);
        return (double)tmp/p;
  }
        //RoundUp Values for Deposit Amount
      public static double Round2(double Rval, int Rpl) {
        double p = (double)Math.pow(10,Rpl);
        Rval = Rval * p;
        double tmp = Math.round(Rval);
        return (double)tmp/p;
  }

    private void ComboRoofTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboRoofTypeActionPerformed
        // On select of item, get price and set Roof type textfield to that price
        try{
            String roofname = ComboRoofType.getSelectedItem().toString();
            String sql = "select roofprice from rooftype where rooftype = '"+roofname+"'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            if(rs.next()){
                String setPrice = rs.getString("roofprice");
                roofPriceTxt.setText(setPrice);
            }

        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_ComboRoofTypeActionPerformed

    private void ComboExtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboExtrasActionPerformed
        // On select of item, get price and set Extra textfield to that price
       try{
            String extraname = ComboExtras.getSelectedItem().toString();
            String sql = "select extraprice from extras where extraname = '"+extraname+"'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            if(rs.next()){
                String setPrice = rs.getString("extraprice");
                extraPriceTxt.setText(setPrice);
            }

        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_ComboExtrasActionPerformed

    private void EmailtxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailtxtFocusLost
       //Get the string for validation
      String email = Emailtxt.getText();

      //Set the email pattern string
      Pattern p = Pattern.compile(".+@.+\\.[a-z]+");

      //Match the given string with the pattern
      Matcher m = p.matcher(email);

      //check whether match is found
      boolean matchFound = m.matches();
      if (matchFound){
            emailErr.setVisible(false);
      }
      else{
        JOptionPane.showMessageDialog(null, "Please input a valid email address.");
        Emailtxt.requestFocusInWindow();
        emailErr.setVisible(true);
      }
    }//GEN-LAST:event_EmailtxtFocusLost

    private void PostcodeTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PostcodeTxtFocusLost
        // TODO add your handling code here:
        //Get Postcode to validate
        String check = PostcodeTxt.getText();
        String regexp="^([A-PR-UWYZ](([0-9](([0-9]|[A-HJKSTUW])?)?)|([A-HK-Y][0-9]([0-9]|[ABEHMNPRVWXY])?)) [0-9][ABD-HJLNP-UW-Z]{2})|GIR 0AA$";

        Pattern pattern = Pattern.compile(regexp);

        Matcher matcher = pattern.matcher(check.toUpperCase());

        if (matcher.matches()) {
                PostcodeErr.setVisible(false);
            }
        else {
                JOptionPane.showMessageDialog(null, "Please input a valid UK Postcode.");
                PostcodeTxt.requestFocusInWindow();
                PostcodeErr.setVisible(true);
            }
    }//GEN-LAST:event_PostcodeTxtFocusLost

    private void PhoneTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PhoneTxtFocusLost
        // TODO add your handling code here:
        String check = PhoneTxt.getText();
        int phonecheck = PhoneTxt.getText().length();
        Pattern pattern = Pattern.compile("\\d{3}-\\d{8}");
        Matcher matcher = pattern.matcher(check);
        if (matcher.matches() && phonecheck == 12) {
            phoneErr.setVisible(false);
    	  }
        else
        {
    	  JOptionPane.showMessageDialog(null,"Phone Number must be 12 digits with '-' in the format XXX-XXXXXXX .");
          PhoneTxt.requestFocusInWindow();
          phoneErr.setVisible(true);
         }
    }//GEN-LAST:event_PhoneTxtFocusLost

    private void QtyTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QtyTxtKeyReleased
        
        //Perform Calculations on input of number in Quantity text field

        double qty = Float.valueOf(QtyTxt.getText());
        double shedPrice = Float.valueOf(shedPriceTxt.getText());
        double roofPrice = Float.valueOf(roofPriceTxt.getText());
        double extraPrice = Float.valueOf(extraPriceTxt.getText());
        double unitPrice = (shedPrice + roofPrice + extraPrice) * qty;
        //call method to round up unit price
        double roundUnitPrice = Round(unitPrice,2);
        String unitPrice1 = String.valueOf(roundUnitPrice);
        UnitPriceTxt.setText(unitPrice1);
        double deposit = 0.1 * unitPrice;
        double subtotal = unitPrice - deposit;
        //call method to round up subtotal amount
        double roundSubtotal = Round1(subtotal,2);
        String subtotal1 = String.valueOf(roundSubtotal);
        String subprice = String.valueOf(subtotal1);
        subtotalTxt.setText(subprice);
        //call method to round up Deposit Amount
        double roundDeposit = Round2(deposit,2);
        String depprice = String.valueOf(roundDeposit);
        DepositTxt.setText(depprice);
//        } else{
//            JOptionPane.showMessageDialog(null, "You can't buy 0 things. Input a number greater than 0");
//        }
    }//GEN-LAST:event_QtyTxtKeyReleased

        public boolean ValidateSurname(){
        boolean check = false;
        String name = SurnameTxt.getText();
        if(name == null || name.length() == 0){
            JOptionPane.showMessageDialog(null, "Surname cannot be empty.");
            SurnameTxt.requestFocusInWindow();
            surnameErr.setVisible(true);
        }
        else{
            check = true;
            surnameErr.setVisible(false);
        }
    return check;
      }


    public boolean ValidateFirstname(){
        boolean check = false;
        String name = FirstnameTxt.getText();
        if(name.length() == 0 || name == null){
            JOptionPane.showMessageDialog(null, "Firstname cannot be empty.");
            FirstnameTxt.requestFocusInWindow();
            firstnameErr.setVisible(true);
        } else{
            check = true;
            firstnameErr.setVisible(false);
        }
        return check;
      }

    public boolean ValidateAddress(){
        boolean check = false;
        String name = AddressTxt.getText();
        if(name.length() == 0 || name == null){
            JOptionPane.showMessageDialog(null, "Address 1 cannot be empty.");
            AddressTxt.requestFocusInWindow();
            AddErr.setVisible(true);
        }else{
            check = true;
            AddErr.setVisible(false);
        }
        return check;
      }

    public boolean ValidateAddress1(){
        boolean check = false;
        String name = Address1Txt.getText();
        if(name.length() == 0 || name == null){
            JOptionPane.showMessageDialog(null, "Address 2 cannot be empty.");
            Address1Txt.requestFocusInWindow();
            Add1Err.setVisible(true);
        } else{
            check = true;
            Add1Err.setVisible(false);
        }
        return check;
      }

//    public boolean ValidateShippingAddress(){
//        boolean check = false;
//        String add = shipAddressTxt.getText();
//        String add1 = shipAddress1Txt.getText();
//        if(shipAddCheck.isSelected()){
//            if(add.length() == 0 || add == null){
//            JOptionPane.showMessageDialog(null, "Shipping Address 1 cannot be empty.");
//            shipAddressTxt.requestFocusInWindow();
//            shipAddErr.setVisible(true);
//          }
//        if(add1.length() == 0 || add1 == null){
//            JOptionPane.showMessageDialog(null, "Shipping Address 2 cannot be empty.");
//            shipAddress1Txt.requestFocusInWindow();
//            shipAdd1Err.setVisible(true);
//         }
//        }
//      }

    public boolean ValidateTown(){
        boolean check = false;
        String name = TownTxt.getText();
        if(name.length() == 0 || name == null){
            JOptionPane.showMessageDialog(null, "Town cannot be empty.");
            TownTxt.requestFocusInWindow();
            TownErr.setVisible(true);
        } else{
            check = true;
            TownErr.setVisible(false);
        }
        return check;
      }

    public boolean ValidatePhone(){
        boolean check = false;
        String name = PhoneTxt.getText();
        if(name.length() == 0 || name == null){
            JOptionPane.showMessageDialog(null, "Telephone cannot be empty.");
            PhoneTxt.requestFocusInWindow();
            phoneErr.setVisible(true);
        } else{
            check = true;
            phoneErr.setVisible(false);
        }
        return check;
      }

    public boolean ValidateQty(){
        boolean check = false;
        String name = QtyTxt.getText();
        int qty = Integer.valueOf(name);
        if(name.length() == 0 || name == null || qty == 0){
            JOptionPane.showMessageDialog(null, "Quantity cannot be empty or 0.");
            QtyTxt.requestFocusInWindow();
            qtyErr.setVisible(true);
        } else{
                 check = true;
        }
    return check;

      }

    public boolean ValidatePostcode(){
        boolean check = false;
        String name = PostcodeTxt.getText();
        if(name == null || name.length() == 0){
            JOptionPane.showMessageDialog(null, "Postcode cannot be empty.");
            PostcodeTxt.requestFocusInWindow();
            PostcodeErr.setVisible(true);
        } else{
            check = true;
            PostcodeErr.setVisible(false);
        }
        return check;
      }

    public boolean ValidateEmail(){
        boolean check = false;
        String name = Emailtxt.getText();
        if(name.length() == 0 || name == null){
            JOptionPane.showMessageDialog(null, "Email cannot be empty.");
            Emailtxt.requestFocusInWindow();
            emailErr.setVisible(true);
        } else{
            check = true;
            emailErr.setVisible(false);
        }
        return check;
      }

   
     public boolean ValidateShedType(){
         boolean check = false;
        int val = ComboShedType.getSelectedIndex();
        if(val == 0){
            JOptionPane.showMessageDialog(null, "Please select a Shed Type.");
            ComboShedType.requestFocusInWindow();
        } else{
            check = true;
        }
        return check;
    }

    public boolean ValidateShedName(){
        boolean check = false;
        int val = ComboShedName.getSelectedIndex();
        if(val == 0){
            JOptionPane.showMessageDialog(null, "Please select a Shed Name.");
            ComboShedName.requestFocusInWindow();
        } else{
            check = true;
        }
        return check;
    }

    public boolean ValidateRooftype(){
        boolean check = false;
        int val = ComboRoofType.getSelectedIndex();
        if(val == 0){
            JOptionPane.showMessageDialog(null, "Please select a Shed Roof.");
            ComboRoofType.requestFocusInWindow();
        } else{
            check = true;
        }
        return check;
    }

    public boolean ValidateExtras(){
        boolean check = false;
        int val = ComboExtras.getSelectedIndex();
        if(val == 0){
            JOptionPane.showMessageDialog(null, "Please select any or no extras as requested.");
            ComboExtras.requestFocusInWindow();
        } else{
            check = true;
        }
        return check;
    }


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminOrderForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add1Err;
    private javax.swing.JLabel AddErr;
    private javax.swing.JTextField Address1Txt;
    private javax.swing.JTextField AddressTxt;
    private javax.swing.JButton BackBtn;
    private javax.swing.JComboBox ComboExtras;
    private javax.swing.JComboBox ComboRoofType;
    private javax.swing.JComboBox ComboShedName;
    private javax.swing.JComboBox ComboShedType;
    private javax.swing.JPanel CustOrderPanel;
    private javax.swing.JScrollPane CustOrderScrollPane;
    private javax.swing.JTextField DepositTxt;
    private javax.swing.JTextField Emailtxt;
    private javax.swing.JLabel ErrorLabel;
    private javax.swing.JTextField FirstnameTxt;
    private javax.swing.JLabel ImageBox;
    private javax.swing.JButton LogOutBtn;
    private javax.swing.JTextField OrderNoTxt;
    private javax.swing.JTextField PhoneTxt;
    private javax.swing.JLabel PostcodeErr;
    private javax.swing.JTextField PostcodeTxt;
    private javax.swing.JTextField QtyTxt;
    private javax.swing.JRadioButton RdBtnDr;
    private javax.swing.JRadioButton RdBtnMa;
    private javax.swing.JRadioButton RdBtnMiss;
    private javax.swing.JRadioButton RdBtnMr;
    private javax.swing.JRadioButton RdBtnMrs;
    private javax.swing.JRadioButton RdBtnSir;
    private javax.swing.JButton ResetBtn;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JTextField SurnameTxt;
    private javax.swing.JLabel TownErr;
    private javax.swing.JTextField TownTxt;
    private javax.swing.JTextField UnitPriceTxt;
    private javax.swing.JLabel emailErr;
    private javax.swing.JTextField extraPriceTxt;
    private javax.swing.JLabel firstnameErr;
    private javax.swing.JDesktopPane imgBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel phoneErr;
    private javax.swing.JLabel qtyErr;
    private javax.swing.JTextField roofPriceTxt;
    private javax.swing.JTextField shedPriceTxt;
    private javax.swing.JLabel shipAdd1Err;
    private javax.swing.JLabel shipAdd1Lbl;
    private javax.swing.JCheckBox shipAddCheck;
    private javax.swing.JLabel shipAddErr;
    private javax.swing.JLabel shipAddLbl;
    private javax.swing.JTextField shipAddress1Txt;
    private javax.swing.JTextField shipAddressTxt;
    private javax.swing.JTextField subtotalTxt;
    private javax.swing.JLabel surnameErr;
    private javax.swing.JLabel titleErr;
    private javax.swing.ButtonGroup titleGrpRdBtn;
    // End of variables declaration//GEN-END:variables

    private String title;
    private ImageIcon image = null;
    int price = 0;
    double shedprice = 0;
    double extraprice = 0;
    double roofprice = 0;
    double RoundTo2Decimals(double val) {
            DecimalFormat df2 = new DecimalFormat("###.##");
        return Double.valueOf(df2.format(val));
}


}
