/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdminPrintCustOrder.java
 *
 * Created on 30-Sep-2012, 09:40:28
 */

package TgsSystem;

import java.sql.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowEvent;

/**
 *
 * @author Babathurpe
 */
public class AdminPrintCustOrder extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /** Creates new form AdminPrintCustOrder */
    public AdminPrintCustOrder() {
        initComponents();
    }

     public void close(){
             WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
             Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
     
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogOutBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        SearchTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        SearchBtn = new javax.swing.JButton();
        ViewOrderScrollPane = new javax.swing.JScrollPane();
        CustInvTxt = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        BtnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manager :: Print Invoice");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        LogOutBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LogOutBtn.setText("Log Out");
        LogOutBtn.setName("LogOutBtn"); // NOI18N
        LogOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBtnActionPerformed(evt);
            }
        });

        BackBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.setName("BackBtn"); // NOI18N
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("TIMBERLAND GARDEN SHEDS ADMIN - VIEW ORDER FORM.");
        jLabel1.setName("jLabel1"); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Aparajita", 1, 18), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel3.setName("jPanel3"); // NOI18N

        SearchTxt.setName("SearchTxt"); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 51));
        jLabel11.setText("Search for orders by Order ID.");
        jLabel11.setName("jLabel11"); // NOI18N

        SearchBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SearchBtn.setText("Search");
        SearchBtn.setName("SearchBtn"); // NOI18N
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(SearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SearchBtn)
                        .addGap(31, 31, 31))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(151, 151, 151))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11))
        );

        ViewOrderScrollPane.setName("ViewOrderScrollPane"); // NOI18N

        CustInvTxt.setColumns(20);
        CustInvTxt.setEditable(false);
        CustInvTxt.setRows(5);
        CustInvTxt.setName("CustInvTxt"); // NOI18N
        ViewOrderScrollPane.setViewportView(CustInvTxt);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Print Customer Invoice", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        BtnPrint.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        BtnPrint.setForeground(new java.awt.Color(255, 0, 153));
        BtnPrint.setText("Print Customer Invoice");
        BtnPrint.setName("BtnPrint"); // NOI18N
        BtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnPrint)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnPrint)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(BackBtn)
                        .addGap(35, 35, 35)
                        .addComponent(LogOutBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ViewOrderScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 929, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(114, 114, 114)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(ViewOrderScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackBtn)
                    .addComponent(LogOutBtn))
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBtnActionPerformed
        // TODO add your handling code here:
        close();
        TgsMainFrame main = new TgsMainFrame();
        main.setVisible(true);
    }//GEN-LAST:event_LogOutBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        close();
        AdminFrame home = new AdminFrame();
        home.setVisible(true);
    }//GEN-LAST:event_BackBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        conn = mysqlconnect.ConnectDb();
    }//GEN-LAST:event_formWindowOpened

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        // TODO add your handling code here:
        CustInvTxt.setText(null);
        try{
            
            //Select all information from table where center name matches
            String sql = "select * from tgscustomerform where orderid=?";
            pst = conn.prepareStatement(sql);
            //Get text from Seacrh textbox
            pst.setString(1, SearchTxt.getText());
            //Search table for center name
            rs = pst.executeQuery();
            //if center name is available
            if(rs.next()){
                String orderId = rs.getString("orderid");
                String firstname = rs.getString("Firstname");
                String surname = rs.getString("Surname");
                String title = rs.getString("Title");
                String address = rs.getString("Address");
                String address1 = rs.getString("Address1");
                String shipadd = rs.getString("shipadd");
                String shipadd1 = rs.getString("shipadd1");
                String town = rs.getString("Town");
                String postcode = rs.getString("Postcode");
                String phone = rs.getString("Phone");
                String email = rs.getString("email");
                String shedtype = rs.getString("shedtype");
                String shedname = rs.getString("shedname");
                String rooftype = rs.getString("rooftype");
                String extras = rs.getString("extras");
                String quantity = rs.getString("quantity");
                String unitprice = rs.getString("unitprice");
                String deposit = rs.getString("deposit");
                String subtotal = rs.getString("subtotal");
                String gardencentername = rs.getString("gardencentername");
                String date = rs.getString("date");
                CustInvTxt.append("\t  TGS CUSTOMER INVOICE FORM \n" +
                        "\t____________________________\n\n");

                CustInvTxt.append("    Thank you for shopping at TGS SHEDS - Customer Satisfaction Guaranteed.\n\n");
                //Fetch and put available data from database and append to text area.
                CustInvTxt.append("    Garden Center Name:\t" + gardencentername +"\n");
                CustInvTxt.append("    Order Date: \t\t" + date + "\n\n");
                CustInvTxt.append("\t Customer Details\n\t__________________\n");
                CustInvTxt.append("    Order Number: \t" + orderId + "\n");
                CustInvTxt.append("    Customer Name: \t" + firstname + "  "+ surname +" \n");
                CustInvTxt.append("    Phone Number: \t" + phone + "\n");
                CustInvTxt.append("    E-Mail: \t\t" + email + "\n");
                CustInvTxt.append("    Address: \t\t" + address + "\n");
                CustInvTxt.append("    Address1: \t\t" + address1 + "\n");
                CustInvTxt.append("    Shipping Address: \t" + shipadd + "\n");
                CustInvTxt.append("    Shipping Address 1: \t" + shipadd1 + "\n");
                CustInvTxt.append("    Town: \t\t" + town + "\n");
                CustInvTxt.append("    Postcode: \t\t" + postcode + "\n\n");
                CustInvTxt.append("\t Products Details\n");
                CustInvTxt.append("\t________________\n");
                CustInvTxt.append("    Shed Type: \t\t" + shedtype + "\n");
                CustInvTxt.append("    Shed Name: \t\t" + shedname + "\n");
                CustInvTxt.append("    Roof Type: \t\t" + rooftype + "\n");
                CustInvTxt.append("    Extras Ordered: \t" + extras + "\n");
                CustInvTxt.append("    Quantity: \t\t" + quantity + "\n");
                CustInvTxt.append("    Unit Price: \t\t" + unitprice + " Pounds\n");
                CustInvTxt.append("    Deposit Paid: \t" + deposit + " Pounds\n");
                CustInvTxt.append("    Amount To Pay: \t" + subtotal + " Pounds\n\n");
                CustInvTxt.append("  Refunds and exchanges can be issued for items with manufacturer's defect.\n  Returns can be made WITHIN 7 DAYS OF PURCHASE by calling our customer care on 074-78635421 or email: tgscustomercare@tgssheds.com\n");
  
            }else
                {
                    JOptionPane.showMessageDialog(null, "Sorry, No match found. Search again.");
                }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void BtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrintActionPerformed
        // TODO add your handling code here:
        String check = CustInvTxt.getText();
        if( check.length() == 0){
            JOptionPane.showMessageDialog(null, "You can not print a blank field.\nSearch for an Order Number and then you can print the Invoice.");
        }
        else{
            try{
                CustInvTxt.print();
            }catch(Exception e){

            }

        }
    }//GEN-LAST:event_BtnPrintActionPerformed

   /** private void UpdateTable(){
        try{
            String sql = "select orderid,firstname,surname,email,subtotal,phone,address,address1,gardencentername from  tgscustomerform";;
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            OrderTable.setModel(DbUtils.resultSetToTableModel(rs));

        } catch(Exception e){

        } finally{
            try{
                rs.close();
                pst.close();
            } catch(Exception e){

            }
        }
    }

    private void CenterUpdateTable(){
        try{
            String center = SearchTxt.getText();
            String sql = "select orderid,firstname,surname,email,subtotal,phone,address,address1,gardencentername from  tgscustomerform where gardencentername = '"+center+"' ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            OrderTable.setModel(DbUtils.resultSetToTableModel(rs));

        } catch(Exception e){

        } finally{
            try{
                rs.close();
                pst.close();
            } catch(Exception e){

            }
        }
    }
    */

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPrintCustOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton BtnPrint;
    private javax.swing.JTextArea CustInvTxt;
    private javax.swing.JButton LogOutBtn;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JTextField SearchTxt;
    private javax.swing.JScrollPane ViewOrderScrollPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

}
