/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdminSupplierInvoice.java
 *
 * Created on 30-Sep-2012, 09:41:59
 */

package TgsSystem;

import java.sql.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowEvent;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Babathurpe
 */
public class AdminSupplierInvoice extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /** Creates new form AdminSupplierInvoice */
    public AdminSupplierInvoice() {
        initComponents();
    }

    public void close(){
             WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
             Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogOutBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        InvoiceScrollPane = new javax.swing.JScrollPane();
        InvoicePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        SupplierTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        AddBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        OrderNoTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ItemTxt = new javax.swing.JTextField();
        SupplierNameTxt = new javax.swing.JTextField();
        UpdateBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        QtyTxt = new javax.swing.JTextField();
        UnitPriceTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TotalTxt = new javax.swing.JTextField();
        DeliveryLbl = new javax.swing.JLabel();
        DeliveryCombo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DeliveryLbl1 = new javax.swing.JLabel();
        DeliveryTxt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        SearchTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        SearchBtn = new javax.swing.JButton();
        dateTxt = new javax.swing.JTextField();
        dateLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manager :: Suppliers' Invoice");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        LogOutBtn.setFont(new java.awt.Font("Tahoma", 1, 11));
        LogOutBtn.setText("Log Out");
        LogOutBtn.setName("LogOutBtn"); // NOI18N
        LogOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBtnActionPerformed(evt);
            }
        });

        BackBtn.setFont(new java.awt.Font("Tahoma", 1, 11));
        BackBtn.setText("Back");
        BackBtn.setName("BackBtn"); // NOI18N
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Modern No. 20", 1, 24));
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("TIMBERLAND GARDEN SHEDS ADMIN - SUPPLIERS' INVOICE.");
        jLabel3.setName("jLabel3"); // NOI18N

        InvoiceScrollPane.setName("InvoiceScrollPane"); // NOI18N

        InvoicePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Suppliers", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Aparajita", 1, 24), new java.awt.Color(153, 51, 0))); // NOI18N
        InvoicePanel.setName("InvoicePanel"); // NOI18N
        InvoicePanel.setPreferredSize(new java.awt.Dimension(407, 310));

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        SupplierTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Order No", "Supplier Name", "Item", "Qty", "Unit Price", "Total", "Delivery Status", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SupplierTable.setName("SupplierTable"); // NOI18N
        jScrollPane2.setViewportView(SupplierTable);

        javax.swing.GroupLayout InvoicePanelLayout = new javax.swing.GroupLayout(InvoicePanel);
        InvoicePanel.setLayout(InvoicePanelLayout);
        InvoicePanelLayout.setHorizontalGroup(
            InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );
        InvoicePanelLayout.setVerticalGroup(
            InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
        );

        InvoiceScrollPane.setViewportView(InvoicePanel);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Supplier Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Aparajita", 1, 18), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel4.setName("jPanel4"); // NOI18N

        AddBtn.setFont(new java.awt.Font("Tahoma", 1, 11));
        AddBtn.setText("Add/Save");
        AddBtn.setName("AddBtn"); // NOI18N
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });

        DeleteBtn.setFont(new java.awt.Font("Tahoma", 1, 11));
        DeleteBtn.setText("Delete");
        DeleteBtn.setName("DeleteBtn"); // NOI18N
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setText("Item:");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel5.setText("Order No:");
        jLabel5.setName("jLabel5"); // NOI18N

        OrderNoTxt.setName("OrderNoTxt"); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel6.setText("Supplier Name:");
        jLabel6.setName("jLabel6"); // NOI18N

        ItemTxt.setName("ItemTxt"); // NOI18N

        SupplierNameTxt.setName("SupplierNameTxt"); // NOI18N

        UpdateBtn.setFont(new java.awt.Font("Tahoma", 1, 11));
        UpdateBtn.setText("Update");
        UpdateBtn.setName("UpdateBtn"); // NOI18N
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel7.setText("Quantity:");
        jLabel7.setName("jLabel7"); // NOI18N

        QtyTxt.setName("QtyTxt"); // NOI18N

        UnitPriceTxt.setName("UnitPriceTxt"); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel8.setText("Unit Price:");
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel9.setText("Total:");
        jLabel9.setName("jLabel9"); // NOI18N

        TotalTxt.setName("TotalTxt"); // NOI18N

        DeliveryLbl.setFont(new java.awt.Font("Tahoma", 1, 11));
        DeliveryLbl.setText("Delivery Status:");
        DeliveryLbl.setName("DeliveryLbl"); // NOI18N

        DeliveryCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Status", "Yes", "No" }));
        DeliveryCombo.setName("DeliveryCombo"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("** Please Fill in all fields. **");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText(" If goods have been supplied, then select appropriate Delivery Status.");
        jLabel2.setName("jLabel2"); // NOI18N

        DeliveryLbl1.setFont(new java.awt.Font("Tahoma", 1, 11));
        DeliveryLbl1.setText("Delivery Status:");
        DeliveryLbl1.setName("DeliveryLbl1"); // NOI18N

        DeliveryTxt.setEditable(false);
        DeliveryTxt.setName("DeliveryTxt"); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Aparajita", 1, 18), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel3.setName("jPanel3"); // NOI18N

        SearchTxt.setName("SearchTxt"); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel11.setForeground(new java.awt.Color(255, 0, 51));
        jLabel11.setText("Search Supplier by Supplier's Order Number.");
        jLabel11.setName("jLabel11"); // NOI18N

        SearchBtn.setFont(new java.awt.Font("Tahoma", 1, 11));
        SearchBtn.setText("Search");
        SearchBtn.setName("SearchBtn"); // NOI18N
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(SearchTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(SearchBtn)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addContainerGap(109, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dateTxt.setEditable(false);
        dateTxt.setName("dateTxt"); // NOI18N

        dateLbl.setFont(new java.awt.Font("Tahoma", 1, 11));
        dateLbl.setText("Date / Time:");
        dateLbl.setName("dateLbl"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(AddBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdateBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeleteBtn))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(DeliveryLbl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeliveryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DeliveryLbl)
                            .addComponent(dateLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DeliveryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(62, 62, 62)
                            .addComponent(TotalTxt))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel4)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8))
                            .addGap(10, 10, 10)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ItemTxt)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(UnitPriceTxt)
                                    .addComponent(QtyTxt)
                                    .addComponent(SupplierNameTxt)
                                    .addComponent(OrderNoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(OrderNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SupplierNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ItemTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QtyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UnitPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DeliveryLbl1)
                            .addComponent(DeliveryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DeliveryLbl)
                            .addComponent(DeliveryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(dateLbl))
                    .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddBtn)
                    .addComponent(UpdateBtn)
                    .addComponent(DeleteBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InvoiceScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(426, 426, 426)
                        .addComponent(BackBtn)
                        .addGap(35, 35, 35)
                        .addComponent(LogOutBtn)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(InvoiceScrollPane))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackBtn)
                    .addComponent(LogOutBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        close();
        AdminFrame home = new AdminFrame();
        home.setVisible(true);
    }//GEN-LAST:event_BackBtnActionPerformed

    private void LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBtnActionPerformed
        // TODO add your handling code here:
        close();
        TgsMainFrame main = new TgsMainFrame();
        main.setVisible(true);
    }//GEN-LAST:event_LogOutBtnActionPerformed


    public boolean ValidateSupplierName(){
        boolean check = false;
        String name = SupplierNameTxt.getText();
        if(name.length() == 0 || name == null){
            JOptionPane.showMessageDialog(null, "Supplier Name cannot be empty.");
            SupplierNameTxt.requestFocusInWindow();
        } else{
            check = true;
        }
        return check;
      }

    
    public boolean ValidateOrderNo(){
        boolean check = false;
        String name = OrderNoTxt.getText();
        if(name.length() == 0 || name == null){
            JOptionPane.showMessageDialog(null, "Order Number cannot be empty.");
            OrderNoTxt.requestFocusInWindow();
        } else{
            check = true;
        }
        return check;
      }
    public boolean ValidateItem(){
        boolean check = false;
        String name = ItemTxt.getText();
        if(name.length() == 0 || name == null){
            JOptionPane.showMessageDialog(null, "Item cannot be empty.");
            ItemTxt.requestFocusInWindow();
        } else{
            check = true;
        }
        return check;
      }
    public boolean ValidateQty(){
        boolean check = false;
        String name = QtyTxt.getText();
        if(name.length() == 0 || name == null){
            JOptionPane.showMessageDialog(null, "Quantity cannot be empty.");
            QtyTxt.requestFocusInWindow();
        } else{
            check = true;
        }
        return check;
      }

    public boolean ValidateUnitPrice(){
        boolean check = false;
        String name = UnitPriceTxt.getText();
        if(name.length() == 0 || name == null){
            JOptionPane.showMessageDialog(null, "Unit Price cannot be empty.");
            UnitPriceTxt.requestFocusInWindow();
        } else{
            check = true;
        }
        return check;
      }

    public boolean ValidateTotal(){
        boolean check = false;
        String name = TotalTxt.getText();
        if(name.length() == 0 || name == null){
            JOptionPane.showMessageDialog(null, "Total cannot be empty.");
            TotalTxt.requestFocusInWindow();
        } else{
            check = true;
        }
        return check;
      }

    public boolean ValidateDelivery(){
        boolean check = false;
        int val = DeliveryCombo.getSelectedIndex();
        if(val == 0){
            JOptionPane.showMessageDialog(null, "Please select Delivery Status.");
            DeliveryCombo.requestFocusInWindow();
        } else{
            check = true;
        }
        return check;
    }


    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:
        java.sql.Date sqlDate = new java.sql.Date(new java.util.Date().getTime());
        if(ValidateOrderNo() && ValidateSupplierName() && ValidateItem() && ValidateQty() && ValidateUnitPrice()
                && ValidateTotal() && ValidateDelivery() ){
        String sql = "insert into suppliers (orderno,supplier_name,item,quantity,unitprice,total,Status,date) values (?,?,?,?,?,?,?,?)";
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1, OrderNoTxt.getText());
            pst.setString(2, SupplierNameTxt.getText());
            pst.setString(3, ItemTxt.getText());
            pst.setString(4, QtyTxt.getText());
            pst.setString(5, UnitPriceTxt.getText());
            pst.setString(6, TotalTxt.getText());
            String value = DeliveryCombo.getSelectedItem().toString();
            pst.setString(7, value);
            pst.setDate(8,sqlDate);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Supplier Info added.");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Please Check for the following errors: \nQuantity, Unit Price and Total must be numbers.\nThere are duplicate order" +
                    " numbers.");
        }
        UpdateTable();
        } 
}//GEN-LAST:event_AddBtnActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        // TODO add your handling code here:
        if(ValidateOrderNo() && ValidateSupplierName() && ValidateItem() && ValidateQty() && ValidateUnitPrice()
                && ValidateTotal() && ValidateDelivery() ){
        try{
            //get values from text fields to be edited.
            String OrderNo = OrderNoTxt.getText();
            String SupplierName = SupplierNameTxt.getText();
            String item = ItemTxt.getText();
            int qty = Integer.parseInt(QtyTxt.getText());
            Float unitprice = Float.valueOf(UnitPriceTxt.getText());
            Float Total = Float.valueOf(TotalTxt.getText());
            String delivery = DeliveryCombo.getSelectedItem().toString();
            //sql statement to be executed
            String sql = "update suppliers set orderno = '"+OrderNo+"',supplier_name = '"+SupplierName+"',item = '"+item+"',quantity = '"+qty+"',unitprice = '"+unitprice+"',total = '"+Total+"',status = '"+delivery+"' where orderno = '"+OrderNo+"' ";
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Supplier Info has been updated.");
            //clear text field and combo box to default null values after update.
            OrderNoTxt.setText(null);
            SupplierNameTxt.setText(null);
            ItemTxt.setText(null);
            QtyTxt.setText(null);
            UnitPriceTxt.setText(null);
            TotalTxt.setText(null);
            DeliveryCombo.setSelectedIndex(0);
            DeliveryTxt.setVisible(false);
            DeliveryLbl1.setVisible(false);
            dateTxt.setVisible(false);
            dateLbl.setVisible(false);
        } catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
        }
        UpdateTable();
      }
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:
            int confirm = JOptionPane.showConfirmDialog(rootPane, "Are you sure?","Delete", JOptionPane.YES_NO_OPTION);
            if(confirm==0){
            String sql = "delete from suppliers where orderno = ? ";
         try{
            pst = conn.prepareStatement(sql);
            pst.setString(1, OrderNoTxt.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Supplier Info has been deleted.");
            // clear text field and combo box to default null values after delete.
            OrderNoTxt.setText(null);
            SupplierNameTxt.setText(null);
            ItemTxt.setText(null);
            QtyTxt.setText(null);
            UnitPriceTxt.setText(null);
            TotalTxt.setText(null);
            DeliveryCombo.setSelectedIndex(0);
            DeliveryTxt.setVisible(false);
            DeliveryLbl1.setVisible(false);
            dateTxt.setVisible(false);
            dateLbl.setVisible(false);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
            UpdateTable();
       }
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        conn = mysqlconnect.ConnectDb();
        DeliveryTxt.setVisible(false);
        DeliveryLbl1.setVisible(false);
        dateLbl.setVisible(false);
        dateTxt.setVisible(false);
        UpdateTable();
    }//GEN-LAST:event_formWindowOpened

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        // TODO add your handling code here:
        try{
             DeliveryTxt.setVisible(true);
             DeliveryLbl1.setVisible(true);
             dateLbl.setVisible(true);
             dateTxt.setVisible(true);
            //Select all information from table where center name matches
            String sql = "select * from suppliers where orderno=?";
            pst = conn.prepareStatement(sql);
            //Get text from Seacrh textbox
            pst.setString(1, SearchTxt.getText());
            //Search table for center name
            rs = pst.executeQuery();
            //if center name is available
            if(rs.next()){
                //Fetch and put available data from table into appropriate fields
                String setId = rs.getString("orderno");
                OrderNoTxt.setText(setId);
                String setSupplierName = rs.getString("supplier_name");
                SupplierNameTxt.setText(setSupplierName);
                String setItem = rs.getString("item");
                ItemTxt.setText(setItem);
                String setQty = rs.getString("quantity");
                QtyTxt.setText(setQty);
                String setUnitPrice = rs.getString("unitprice");
                UnitPriceTxt.setText(setUnitPrice);
                String setTotal = rs.getString("total");
                TotalTxt.setText(setTotal);
                String status = rs.getString("Status");
                DeliveryTxt.setText(status);
                String date = rs.getString("date");
                dateTxt.setText(date);
            }else{
                UpdateTable();
                JOptionPane.showMessageDialog(null, "Sorry, No match found. Search again.");
                DeliveryTxt.setVisible(false);
                DeliveryLbl1.setVisible(false);
                dateLbl.setVisible(false);
                dateTxt.setVisible(false);
                OrderNoTxt.setText(null);
                SupplierNameTxt.setText(null);
                ItemTxt.setText(null);
                QtyTxt.setText(null);
                UnitPriceTxt.setText(null);
                TotalTxt.setText(null);
                DeliveryCombo.setSelectedIndex(0);
          }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_SearchBtnActionPerformed

    private void UpdateTable(){
        try{
            String sql = "select * from suppliers";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            SupplierTable.setModel(DbUtils.resultSetToTableModel(rs));

        } catch(Exception e){

        } finally{
            try{
                rs.close();
                pst.close();
            } catch(Exception e){

            }
        }
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSupplierInvoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JComboBox DeliveryCombo;
    private javax.swing.JLabel DeliveryLbl;
    private javax.swing.JLabel DeliveryLbl1;
    private javax.swing.JTextField DeliveryTxt;
    private javax.swing.JPanel InvoicePanel;
    private javax.swing.JScrollPane InvoiceScrollPane;
    private javax.swing.JTextField ItemTxt;
    private javax.swing.JButton LogOutBtn;
    private javax.swing.JTextField OrderNoTxt;
    private javax.swing.JTextField QtyTxt;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JTextField SearchTxt;
    private javax.swing.JTextField SupplierNameTxt;
    private javax.swing.JTable SupplierTable;
    private javax.swing.JTextField TotalTxt;
    private javax.swing.JTextField UnitPriceTxt;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JTextField dateTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
