/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdminFrame.java
 *
 * Created on 27-Sep-2012, 00:48:34
 */

package TgsSystem;

import java.sql.*;
import java.awt.*;
import java.awt.event.*;
/**
 *
 * @author Babathurpe
 */
public class AdminFrame extends javax.swing.JFrame {

        Connection conn = null;
        ResultSet rs = null;
        PreparedStatement pst = null;

    /** Creates new form AdminFrame */
    public AdminFrame() {
        initComponents();
    }

     public void close(){
             WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
             Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnCustForm = new javax.swing.JButton();
        BtnPrintCustInv = new javax.swing.JButton();
        BtnStatements = new javax.swing.JButton();
        BtnPayroll = new javax.swing.JButton();
        BtnInvoices = new javax.swing.JButton();
        UpdateCenterBtn = new javax.swing.JButton();
        BtnViewSuppliers = new javax.swing.JButton();
        BtnLogOut = new javax.swing.JButton();
        AddProdBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TGS :: Manager Home");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Main Menu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Aharoni", 1, 24), new java.awt.Color(255, 102, 0))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.setName("jPanel1"); // NOI18N

        BtnCustForm.setFont(new java.awt.Font("Bodoni MT", 1, 36)); // NOI18N
        BtnCustForm.setForeground(new java.awt.Color(0, 102, 102));
        BtnCustForm.setText("Customer Order Form");
        BtnCustForm.setToolTipText("");
        BtnCustForm.setName("BtnCustForm"); // NOI18N
        BtnCustForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCustFormActionPerformed(evt);
            }
        });

        BtnPrintCustInv.setFont(new java.awt.Font("Bodoni MT", 1, 36)); // NOI18N
        BtnPrintCustInv.setForeground(new java.awt.Color(0, 102, 102));
        BtnPrintCustInv.setText("Print Customer Orders");
        BtnPrintCustInv.setName("BtnPrintCustInv"); // NOI18N
        BtnPrintCustInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrintCustInvActionPerformed(evt);
            }
        });

        BtnStatements.setFont(new java.awt.Font("Bodoni MT", 1, 36)); // NOI18N
        BtnStatements.setForeground(new java.awt.Color(0, 102, 102));
        BtnStatements.setText("Centers' Commission");
        BtnStatements.setName("BtnStatements"); // NOI18N
        BtnStatements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnStatementsActionPerformed(evt);
            }
        });

        BtnPayroll.setFont(new java.awt.Font("Bodoni MT", 1, 36)); // NOI18N
        BtnPayroll.setForeground(new java.awt.Color(0, 102, 102));
        BtnPayroll.setText("Workers' Payroll");
        BtnPayroll.setName("BtnPayroll"); // NOI18N
        BtnPayroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPayrollActionPerformed(evt);
            }
        });

        BtnInvoices.setFont(new java.awt.Font("Bodoni MT", 1, 36)); // NOI18N
        BtnInvoices.setForeground(new java.awt.Color(0, 102, 102));
        BtnInvoices.setText("Customer Invoices");
        BtnInvoices.setName("BtnInvoices"); // NOI18N
        BtnInvoices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInvoicesActionPerformed(evt);
            }
        });

        UpdateCenterBtn.setFont(new java.awt.Font("Bodoni MT", 1, 36)); // NOI18N
        UpdateCenterBtn.setForeground(new java.awt.Color(0, 102, 102));
        UpdateCenterBtn.setText("Add/Delete Garden Centers");
        UpdateCenterBtn.setName("UpdateCenterBtn"); // NOI18N
        UpdateCenterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateCenterBtnActionPerformed(evt);
            }
        });

        BtnViewSuppliers.setFont(new java.awt.Font("Bodoni MT", 1, 36)); // NOI18N
        BtnViewSuppliers.setForeground(new java.awt.Color(0, 102, 102));
        BtnViewSuppliers.setText("View Suppliers' Invoices");
        BtnViewSuppliers.setName("BtnViewSuppliers"); // NOI18N
        BtnViewSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewSuppliersActionPerformed(evt);
            }
        });

        BtnLogOut.setFont(new java.awt.Font("Bodoni MT", 1, 36)); // NOI18N
        BtnLogOut.setForeground(new java.awt.Color(0, 102, 102));
        BtnLogOut.setText("Log Out");
        BtnLogOut.setName("BtnLogOut"); // NOI18N
        BtnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogOutActionPerformed(evt);
            }
        });

        AddProdBtn.setFont(new java.awt.Font("Bodoni MT", 1, 36)); // NOI18N
        AddProdBtn.setForeground(new java.awt.Color(0, 102, 102));
        AddProdBtn.setText("Add Products");
        AddProdBtn.setName("AddProdBtn"); // NOI18N
        AddProdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProdBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnLogOut)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnPrintCustInv)
                            .addComponent(AddProdBtn)
                            .addComponent(BtnViewSuppliers)
                            .addComponent(BtnCustForm))
                        .addGap(102, 102, 102)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnStatements)
                            .addComponent(UpdateCenterBtn)
                            .addComponent(BtnPayroll)
                            .addComponent(BtnInvoices))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnInvoices)
                    .addComponent(BtnCustForm))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnPrintCustInv)
                    .addComponent(BtnPayroll))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddProdBtn)
                    .addComponent(UpdateCenterBtn))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnViewSuppliers)
                    .addComponent(BtnStatements))
                .addGap(54, 54, 54)
                .addComponent(BtnLogOut)
                .addGap(74, 74, 74))
        );

        jLabel1.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("TIMBERLAND GARDEN SHEDS ::: WELCOME TO ADMIN HOME.");
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogOutActionPerformed
        // TODO add your handling code here:
        close();
        TgsMainFrame tgsmain = new TgsMainFrame();
        tgsmain.setVisible(true);
    }//GEN-LAST:event_BtnLogOutActionPerformed

    private void BtnCustFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCustFormActionPerformed
        // TODO add your handling code here:
        close();
        AdminOrderForm custOrderForm = new AdminOrderForm();
        custOrderForm.setVisible(true);
    }//GEN-LAST:event_BtnCustFormActionPerformed

    private void BtnPrintCustInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrintCustInvActionPerformed
        // TODO add your handling code here:
        close();
        AdminPrintCustOrder viewOrder = new AdminPrintCustOrder();
        viewOrder.setVisible(true);
}//GEN-LAST:event_BtnPrintCustInvActionPerformed

    private void BtnStatementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnStatementsActionPerformed
        // TODO add your handling code here:
        close();
        AdminCommissionStatement debtor = new AdminCommissionStatement();
        debtor.setVisible(true);
    }//GEN-LAST:event_BtnStatementsActionPerformed

    private void BtnPayrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPayrollActionPerformed
        // TODO add your handling code here:
        close();
        AdminPayroll payroll = new AdminPayroll();
        payroll.setVisible(true);
    }//GEN-LAST:event_BtnPayrollActionPerformed

    private void BtnInvoicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInvoicesActionPerformed
        // TODO add your handling code here:
        close();
        AdminCustOrderInvoice custInv = new AdminCustOrderInvoice();
        custInv.setVisible(true);
    }//GEN-LAST:event_BtnInvoicesActionPerformed

    private void BtnViewSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewSuppliersActionPerformed
        // TODO add your handling code here:
        close();
        AdminSupplierInvoice supplierInv = new AdminSupplierInvoice();
        supplierInv.setVisible(true);
    }//GEN-LAST:event_BtnViewSuppliersActionPerformed

    private void UpdateCenterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateCenterBtnActionPerformed
        // TODO add your handling code here:
        close();
        AdminUpdateCenter updateCenter = new AdminUpdateCenter();
        updateCenter.setVisible(true);
}//GEN-LAST:event_UpdateCenterBtnActionPerformed

    private void AddProdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProdBtnActionPerformed
        // TODO add your handling code here:
        close();
        AddProduct addProd = new AddProduct();
        addProd.setVisible(true);
}//GEN-LAST:event_AddProdBtnActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddProdBtn;
    private javax.swing.JButton BtnCustForm;
    private javax.swing.JButton BtnInvoices;
    private javax.swing.JButton BtnLogOut;
    private javax.swing.JButton BtnPayroll;
    private javax.swing.JButton BtnPrintCustInv;
    private javax.swing.JButton BtnStatements;
    private javax.swing.JButton BtnViewSuppliers;
    private javax.swing.JButton UpdateCenterBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
