/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CenterHomeFrame.java
 *
 * Created on 28-Sep-2012, 11:17:52
 */

package TgsSystem;


import java.awt.*;
import java.awt.event.*;
/**
 *
 * @author Babathurpe
 */
public class CenterHomeFrame extends javax.swing.JFrame {

    /** Creates new form CenterHomeFrame */
    public CenterHomeFrame() {
        initComponents();
    }

     public void close(){
             WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
             Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnGrpTitle = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        BtnCustForm = new javax.swing.JButton();
        BtnStatements = new javax.swing.JButton();
        BtnLogOut = new javax.swing.JButton();
        BtnInvoices = new javax.swing.JButton();
        BtnPrintInv = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TGS CENTER HOME");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Main Menu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Aharoni", 1, 24), new java.awt.Color(255, 102, 0))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.setName("jPanel1"); // NOI18N

        BtnCustForm.setFont(new java.awt.Font("Bodoni MT", 1, 36));
        BtnCustForm.setForeground(new java.awt.Color(0, 102, 102));
        BtnCustForm.setText("Customer Form");
        BtnCustForm.setName("BtnCustForm"); // NOI18N
        BtnCustForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCustFormActionPerformed(evt);
            }
        });

        BtnStatements.setFont(new java.awt.Font("Bodoni MT", 1, 36)); // NOI18N
        BtnStatements.setForeground(new java.awt.Color(0, 102, 102));
        BtnStatements.setText("Commission Statement");
        BtnStatements.setName("BtnStatements"); // NOI18N
        BtnStatements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnStatementsActionPerformed(evt);
            }
        });

        BtnLogOut.setFont(new java.awt.Font("Bodoni MT", 1, 36));
        BtnLogOut.setForeground(new java.awt.Color(0, 102, 102));
        BtnLogOut.setText("Log Out");
        BtnLogOut.setName("BtnLogOut"); // NOI18N
        BtnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogOutActionPerformed(evt);
            }
        });

        BtnInvoices.setFont(new java.awt.Font("Bodoni MT", 1, 36)); // NOI18N
        BtnInvoices.setForeground(new java.awt.Color(0, 102, 102));
        BtnInvoices.setText("View Customer Invoice");
        BtnInvoices.setName("BtnInvoices"); // NOI18N
        BtnInvoices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInvoicesActionPerformed(evt);
            }
        });

        BtnPrintInv.setFont(new java.awt.Font("Bodoni MT", 1, 36)); // NOI18N
        BtnPrintInv.setForeground(new java.awt.Color(0, 102, 102));
        BtnPrintInv.setText("Print Customer Invoice");
        BtnPrintInv.setName("BtnPrintInv"); // NOI18N
        BtnPrintInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrintInvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnCustForm)
                            .addComponent(BtnInvoices))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnStatements)
                            .addComponent(BtnPrintInv)))
                    .addComponent(BtnLogOut))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnPrintInv)
                        .addGap(53, 53, 53)
                        .addComponent(BtnStatements))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnCustForm)
                        .addGap(53, 53, 53)
                        .addComponent(BtnInvoices)))
                .addGap(50, 50, 50)
                .addComponent(BtnLogOut)
                .addGap(116, 116, 116))
        );

        jLabel1.setFont(new java.awt.Font("Modern No. 20", 1, 24));
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Welcome to TIMBERLAND GARDEN SHEDS Center Home Menu.");
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCustFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCustFormActionPerformed
        // TODO add your handling code here:
        close();
        CenterOrderForm order = new CenterOrderForm();
        order.setVisible(true);
       
    }//GEN-LAST:event_BtnCustFormActionPerformed

    private void BtnStatementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnStatementsActionPerformed
        // TODO add your handling code here:
        close();
        CenterComStatement commission = new CenterComStatement();
        commission.setVisible(true);
      
    }//GEN-LAST:event_BtnStatementsActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formWindowOpened

    private void BtnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogOutActionPerformed
        // TODO add your handling code here:
        close();
        TgsMainFrame tgsmain = new TgsMainFrame();
        tgsmain.setVisible(true);
}//GEN-LAST:event_BtnLogOutActionPerformed

    private void BtnInvoicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInvoicesActionPerformed
        // TODO add your handling code here:
        close();
        CenterViewInvFrame custInv = new CenterViewInvFrame();
        custInv.setVisible(true);
}//GEN-LAST:event_BtnInvoicesActionPerformed

    private void BtnPrintInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrintInvActionPerformed
        // TODO add your handling code here:
        close();
        CenterPrintCustOrder printInv = new CenterPrintCustOrder();
        printInv.setVisible(true);
}//GEN-LAST:event_BtnPrintInvActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CenterHomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCustForm;
    private javax.swing.ButtonGroup BtnGrpTitle;
    private javax.swing.JButton BtnInvoices;
    private javax.swing.JButton BtnLogOut;
    private javax.swing.JButton BtnPrintInv;
    private javax.swing.JButton BtnStatements;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
