/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CenterOrderForm.java
 *
 * Created on 30-Sep-2012, 08:12:14
 */

package TgsSystem;

import java.sql.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowEvent;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author Babathurpe
 */
public class CenterOrderForm extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    /** Creates new form CenterOrderForm */
    public CenterOrderForm() {
        initComponents();
    }

    public void close(){
             WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
             Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleGrpRdBtn = new javax.swing.ButtonGroup();
        CustOrderScrollPane = new javax.swing.JScrollPane();
        CustOrderPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        OrderNoTxt = new javax.swing.JTextField();
        SurnameTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        AddressTxt = new javax.swing.JTextField();
        shipAddress1Txt = new javax.swing.JTextField();
        shipAdd1Lbl = new javax.swing.JLabel();
        TownTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        PostcodeTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        PhoneTxt = new javax.swing.JTextField();
        Emailtxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        QtyTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        FirstnameTxt = new javax.swing.JTextField();
        RdBtnMr = new javax.swing.JRadioButton();
        RdBtnMrs = new javax.swing.JRadioButton();
        RdBtnMiss = new javax.swing.JRadioButton();
        RdBtnSir = new javax.swing.JRadioButton();
        RdBtnMa = new javax.swing.JRadioButton();
        RdBtnDr = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        UnitPriceTxt = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        subtotalTxt = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        ComboShedType = new javax.swing.JComboBox();
        ComboShedName = new javax.swing.JComboBox();
        ComboRoofType = new javax.swing.JComboBox();
        ComboExtras = new javax.swing.JComboBox();
        ComboGardenCenter = new javax.swing.JComboBox();
        DepositTxt = new javax.swing.JTextField();
        surnameErr = new javax.swing.JLabel();
        AddErr = new javax.swing.JLabel();
        TownErr = new javax.swing.JLabel();
        Add1Err = new javax.swing.JLabel();
        PostcodeErr = new javax.swing.JLabel();
        phoneErr = new javax.swing.JLabel();
        qtyErr = new javax.swing.JLabel();
        centerErr = new javax.swing.JLabel();
        titleErr = new javax.swing.JLabel();
        Address1Txt = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        shipAddressTxt = new javax.swing.JTextField();
        shipAddLbl = new javax.swing.JLabel();
        shipAddCheck = new javax.swing.JCheckBox();
        shipAdd1Err = new javax.swing.JLabel();
        shipAddErr = new javax.swing.JLabel();
        emailErr = new javax.swing.JLabel();
        firstnameErr = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        imgBox = new javax.swing.JDesktopPane();
        ImageBox = new javax.swing.JLabel();
        shedPriceTxt = new javax.swing.JTextField();
        roofPriceTxt = new javax.swing.JTextField();
        extraPriceTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LogOutBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        ErrorLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TGS Center :: Customer Order Form");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        CustOrderScrollPane.setName("CustOrderScrollPane"); // NOI18N
        CustOrderScrollPane.setPreferredSize(new java.awt.Dimension(502, 750));

        CustOrderPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CustOrderPanel.setName("CustOrderPanel"); // NOI18N
        CustOrderPanel.setPreferredSize(new java.awt.Dimension(500, 750));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Order Number:");
        jLabel2.setName("jLabel2"); // NOI18N

        OrderNoTxt.setEditable(false);
        OrderNoTxt.setName("OrderNoTxt"); // NOI18N

        SurnameTxt.setName("SurnameTxt"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("Surname:");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel5.setText("Address 1:");
        jLabel5.setName("jLabel5"); // NOI18N

        AddressTxt.setName("AddressTxt"); // NOI18N

        shipAddress1Txt.setName("shipAddress1Txt"); // NOI18N

        shipAdd1Lbl.setFont(new java.awt.Font("Tahoma", 1, 11));
        shipAdd1Lbl.setText("Ship to Address 2:");
        shipAdd1Lbl.setName("shipAdd1Lbl"); // NOI18N

        TownTxt.setName("TownTxt"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel7.setText("Town:");
        jLabel7.setName("jLabel7"); // NOI18N

        PostcodeTxt.setName("PostcodeTxt"); // NOI18N
        PostcodeTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                PostcodeTxtFocusLost(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel8.setText("Postcode:");
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel9.setText("Telephone:");
        jLabel9.setName("jLabel9"); // NOI18N

        PhoneTxt.setName("PhoneTxt"); // NOI18N
        PhoneTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                PhoneTxtFocusLost(evt);
            }
        });

        Emailtxt.setName("Emailtxt"); // NOI18N
        Emailtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                EmailtxtFocusLost(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Email:");
        jLabel10.setName("jLabel10"); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel11.setText("Shed Type:");
        jLabel11.setName("jLabel11"); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel12.setText("Shed Name:");
        jLabel12.setName("jLabel12"); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel14.setText("Roof Type:");
        jLabel14.setName("jLabel14"); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel15.setText("Extras:");
        jLabel15.setName("jLabel15"); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel16.setText("Quantity:");
        jLabel16.setName("jLabel16"); // NOI18N

        QtyTxt.setName("QtyTxt"); // NOI18N
        QtyTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                QtyTxtKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setText("Firstname:");
        jLabel4.setName("jLabel4"); // NOI18N

        FirstnameTxt.setName("FirstnameTxt"); // NOI18N

        titleGrpRdBtn.add(RdBtnMr);
        RdBtnMr.setText("Mr");
        RdBtnMr.setName("RdBtnMr"); // NOI18N
        RdBtnMr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdBtnMrActionPerformed(evt);
            }
        });

        titleGrpRdBtn.add(RdBtnMrs);
        RdBtnMrs.setText("Mrs");
        RdBtnMrs.setName("RdBtnMrs"); // NOI18N
        RdBtnMrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdBtnMrsActionPerformed(evt);
            }
        });

        titleGrpRdBtn.add(RdBtnMiss);
        RdBtnMiss.setText("Miss");
        RdBtnMiss.setName("RdBtnMiss"); // NOI18N
        RdBtnMiss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdBtnMissActionPerformed(evt);
            }
        });

        titleGrpRdBtn.add(RdBtnSir);
        RdBtnSir.setText("Sir");
        RdBtnSir.setName("RdBtnSir"); // NOI18N
        RdBtnSir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdBtnSirActionPerformed(evt);
            }
        });

        titleGrpRdBtn.add(RdBtnMa);
        RdBtnMa.setText("Ma");
        RdBtnMa.setName("RdBtnMa"); // NOI18N
        RdBtnMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdBtnMaActionPerformed(evt);
            }
        });

        titleGrpRdBtn.add(RdBtnDr);
        RdBtnDr.setText("Dr");
        RdBtnDr.setName("RdBtnDr"); // NOI18N
        RdBtnDr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdBtnDrActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel17.setForeground(new java.awt.Color(204, 0, 51));
        jLabel17.setText("Customer Details");
        jLabel17.setName("jLabel17"); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel18.setText("Unit Price:");
        jLabel18.setName("jLabel18"); // NOI18N

        UnitPriceTxt.setEditable(false);
        UnitPriceTxt.setName("UnitPriceTxt"); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel19.setText("Deposit:");
        jLabel19.setName("jLabel19"); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel20.setText("Subtotal:");
        jLabel20.setName("jLabel20"); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel22.setText("Garden Center:");
        jLabel22.setName("jLabel22"); // NOI18N

        subtotalTxt.setEditable(false);
        subtotalTxt.setName("subtotalTxt"); // NOI18N

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel23.setForeground(new java.awt.Color(204, 0, 51));
        jLabel23.setText("Garden Center Details");
        jLabel23.setName("jLabel23"); // NOI18N

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel24.setForeground(new java.awt.Color(204, 0, 51));
        jLabel24.setText("Product Details");
        jLabel24.setName("jLabel24"); // NOI18N

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel25.setText("Title:");
        jLabel25.setName("jLabel25"); // NOI18N

        ComboShedType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Shed type" }));
        ComboShedType.setName("ComboShedType"); // NOI18N

        ComboShedName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Product Name" }));
        ComboShedName.setName("ComboShedName"); // NOI18N
        ComboShedName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboShedNameActionPerformed(evt);
            }
        });

        ComboRoofType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Roof Type" }));
        ComboRoofType.setName("ComboRoofType"); // NOI18N
        ComboRoofType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboRoofTypeActionPerformed(evt);
            }
        });

        ComboExtras.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Extras" }));
        ComboExtras.setName("ComboExtras"); // NOI18N
        ComboExtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboExtrasActionPerformed(evt);
            }
        });

        ComboGardenCenter.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Center Name", "Bolton", "Manchester", "Wigan" }));
        ComboGardenCenter.setName("ComboGardenCenter"); // NOI18N
        ComboGardenCenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboGardenCenterActionPerformed(evt);
            }
        });

        DepositTxt.setEditable(false);
        DepositTxt.setName("DepositTxt"); // NOI18N

        surnameErr.setForeground(new java.awt.Color(204, 0, 0));
        surnameErr.setText("***");
        surnameErr.setName("surnameErr"); // NOI18N

        AddErr.setForeground(new java.awt.Color(204, 0, 0));
        AddErr.setText("***");
        AddErr.setName("AddErr"); // NOI18N

        TownErr.setForeground(new java.awt.Color(204, 0, 0));
        TownErr.setText("***");
        TownErr.setName("TownErr"); // NOI18N

        Add1Err.setForeground(new java.awt.Color(204, 0, 0));
        Add1Err.setText("***");
        Add1Err.setName("Add1Err"); // NOI18N

        PostcodeErr.setForeground(new java.awt.Color(204, 0, 0));
        PostcodeErr.setText("***");
        PostcodeErr.setName("PostcodeErr"); // NOI18N

        phoneErr.setForeground(new java.awt.Color(204, 0, 0));
        phoneErr.setText("***");
        phoneErr.setName("phoneErr"); // NOI18N

        qtyErr.setForeground(new java.awt.Color(204, 0, 0));
        qtyErr.setText("***");
        qtyErr.setName("qtyErr"); // NOI18N

        centerErr.setForeground(new java.awt.Color(204, 0, 0));
        centerErr.setText("***");
        centerErr.setName("centerErr"); // NOI18N

        titleErr.setForeground(new java.awt.Color(204, 0, 0));
        titleErr.setText("***");
        titleErr.setName("titleErr"); // NOI18N

        Address1Txt.setName("Address1Txt"); // NOI18N

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel26.setText("Address 2:");
        jLabel26.setName("jLabel26"); // NOI18N

        shipAddressTxt.setName("shipAddressTxt"); // NOI18N

        shipAddLbl.setFont(new java.awt.Font("Tahoma", 1, 11));
        shipAddLbl.setText("Ship to Address 1:");
        shipAddLbl.setName("shipAddLbl"); // NOI18N

        shipAddCheck.setFont(new java.awt.Font("Tahoma", 1, 11));
        shipAddCheck.setForeground(new java.awt.Color(204, 0, 0));
        shipAddCheck.setText("Ship To Different Address?");
        shipAddCheck.setName("shipAddCheck"); // NOI18N
        shipAddCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shipAddCheckActionPerformed(evt);
            }
        });

        shipAdd1Err.setForeground(new java.awt.Color(204, 0, 0));
        shipAdd1Err.setText("***");
        shipAdd1Err.setName("shipAdd1Err"); // NOI18N

        shipAddErr.setForeground(new java.awt.Color(204, 0, 0));
        shipAddErr.setText("***");
        shipAddErr.setName("shipAddErr"); // NOI18N

        emailErr.setForeground(new java.awt.Color(204, 0, 0));
        emailErr.setText("***");
        emailErr.setName("emailErr"); // NOI18N

        firstnameErr.setForeground(new java.awt.Color(204, 0, 0));
        firstnameErr.setText("***");
        firstnameErr.setName("firstnameErr"); // NOI18N

        saveBtn.setFont(new java.awt.Font("Tahoma", 1, 11));
        saveBtn.setForeground(new java.awt.Color(102, 0, 102));
        saveBtn.setText("Submit");
        saveBtn.setName("saveBtn"); // NOI18N
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        resetBtn.setFont(new java.awt.Font("Tahoma", 1, 11));
        resetBtn.setForeground(new java.awt.Color(102, 0, 102));
        resetBtn.setText("Reset");
        resetBtn.setName("resetBtn"); // NOI18N
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        imgBox.setName("imgBox"); // NOI18N

        ImageBox.setName("ImageBox"); // NOI18N
        ImageBox.setBounds(10, 10, 200, 180);
        imgBox.add(ImageBox, javax.swing.JLayeredPane.DEFAULT_LAYER);

        shedPriceTxt.setEditable(false);
        shedPriceTxt.setName("shedPriceTxt"); // NOI18N

        roofPriceTxt.setEditable(false);
        roofPriceTxt.setName("roofPriceTxt"); // NOI18N

        extraPriceTxt.setEditable(false);
        extraPriceTxt.setName("extraPriceTxt"); // NOI18N

        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("XXX-XXXXXXX");
        jLabel6.setName("jLabel6"); // NOI18N

        javax.swing.GroupLayout CustOrderPanelLayout = new javax.swing.GroupLayout(CustOrderPanel);
        CustOrderPanel.setLayout(CustOrderPanelLayout);
        CustOrderPanelLayout.setHorizontalGroup(
            CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustOrderPanelLayout.createSequentialGroup()
                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CustOrderPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(CustOrderPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(OrderNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel23)
                            .addComponent(shipAdd1Lbl)
                            .addGroup(CustOrderPanelLayout.createSequentialGroup()
                                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26))
                                .addGap(46, 46, 46)
                                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Address1Txt)
                                    .addComponent(AddressTxt)
                                    .addGroup(CustOrderPanelLayout.createSequentialGroup()
                                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CustOrderPanelLayout.createSequentialGroup()
                                                .addComponent(SurnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(surnameErr))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CustOrderPanelLayout.createSequentialGroup()
                                                .addComponent(RdBtnMr)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(RdBtnMrs)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(RdBtnMiss)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(RdBtnSir)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(RdBtnMa)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RdBtnDr)
                                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(CustOrderPanelLayout.createSequentialGroup()
                                                .addGap(56, 56, 56)
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(FirstnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(CustOrderPanelLayout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(titleErr)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstnameErr)
                                    .addComponent(Add1Err)
                                    .addComponent(AddErr)))
                            .addGroup(CustOrderPanelLayout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(shipAddCheck))
                            .addGroup(CustOrderPanelLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboGardenCenter, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(centerErr))
                            .addGroup(CustOrderPanelLayout.createSequentialGroup()
                                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(shipAddLbl)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CustOrderPanelLayout.createSequentialGroup()
                                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(PhoneTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TownTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TownErr)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(phoneErr)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel10))
                                        .addGap(18, 18, 18)
                                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Emailtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                            .addComponent(PostcodeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                                    .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(shipAddress1Txt, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(shipAddressTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)))
                                .addGap(25, 25, 25)
                                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(shipAdd1Err)
                                    .addComponent(shipAddErr)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(emailErr, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PostcodeErr, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(CustOrderPanelLayout.createSequentialGroup()
                                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addGroup(CustOrderPanelLayout.createSequentialGroup()
                                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel12)
                                                .addComponent(jLabel11))
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel16))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(CustOrderPanelLayout.createSequentialGroup()
                                                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(ComboShedType, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(ComboExtras, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(ComboShedName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(extraPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(shedPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(CustOrderPanelLayout.createSequentialGroup()
                                                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(UnitPriceTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(QtyTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                                                    .addComponent(DepositTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(subtotalTxt, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(qtyErr))))
                                    .addGroup(CustOrderPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ComboRoofType, 0, 282, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(roofPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(imgBox, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(CustOrderPanelLayout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(saveBtn)
                        .addGap(33, 33, 33)
                        .addComponent(resetBtn)))
                .addContainerGap(34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        CustOrderPanelLayout.setVerticalGroup(
            CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustOrderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(OrderNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addGap(13, 13, 13)
                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RdBtnMr)
                    .addComponent(RdBtnMrs)
                    .addComponent(RdBtnMiss)
                    .addComponent(RdBtnSir)
                    .addComponent(RdBtnMa)
                    .addComponent(RdBtnDr)
                    .addComponent(jLabel25)
                    .addComponent(titleErr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SurnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(surnameErr))
                    .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(FirstnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(firstnameErr)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(AddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddErr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(Address1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add1Err))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shipAddCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shipAddLbl)
                    .addComponent(shipAddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shipAddErr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shipAdd1Lbl)
                    .addComponent(shipAddress1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shipAdd1Err))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CustOrderPanelLayout.createSequentialGroup()
                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(TownTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TownErr))
                        .addGap(6, 6, 6)
                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6)
                            .addComponent(phoneErr, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CustOrderPanelLayout.createSequentialGroup()
                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(PostcodeErr)
                            .addComponent(PostcodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailErr)
                            .addComponent(Emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CustOrderPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addGap(12, 12, 12)
                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(ComboShedType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(ComboShedName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shedPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(ComboRoofType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roofPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(ComboExtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(extraPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(qtyErr)
                            .addComponent(QtyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(UnitPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(DepositTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(subtotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23))
                    .addGroup(CustOrderPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(imgBox, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(ComboGardenCenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(centerErr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(CustOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetBtn)
                    .addComponent(saveBtn))
                .addGap(34, 34, 34))
        );

        CustOrderScrollPane.setViewportView(CustOrderPanel);

        jLabel1.setFont(new java.awt.Font("Modern No. 20", 1, 24));
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("TIMBERLAND GARDEN SHEDS - CUSTOMER ORDER FORM.");
        jLabel1.setName("jLabel1"); // NOI18N

        LogOutBtn.setFont(new java.awt.Font("Tahoma", 1, 11));
        LogOutBtn.setText("Log Out");
        LogOutBtn.setName("LogOutBtn"); // NOI18N
        LogOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBtnActionPerformed(evt);
            }
        });

        BackBtn.setFont(new java.awt.Font("Tahoma", 1, 11));
        BackBtn.setText("Back");
        BackBtn.setName("BackBtn"); // NOI18N
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel21.setForeground(new java.awt.Color(204, 0, 0));
        jLabel21.setText("** All fields are required. **");
        jLabel21.setName("jLabel21"); // NOI18N

        ErrorLbl.setFont(new java.awt.Font("Tahoma", 1, 11));
        ErrorLbl.setForeground(new java.awt.Color(204, 0, 0));
        ErrorLbl.setText("Please Fill in the fields marked ***");
        ErrorLbl.setName("ErrorLbl"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ErrorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CustOrderScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(BackBtn)
                        .addGap(58, 58, 58)
                        .addComponent(LogOutBtn)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ErrorLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CustOrderScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackBtn)
                    .addComponent(LogOutBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBtnActionPerformed
        // TODO add your handling code here:
        close();
        TgsMainFrame main = new TgsMainFrame();
        main.setVisible(true);
    }//GEN-LAST:event_LogOutBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        close();
        CenterHomeFrame home = new CenterHomeFrame();
        home.setVisible(true);
    }//GEN-LAST:event_BackBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        int orderNo = (int)(Math.round(Math.random() * 100000));
        String order = String.valueOf(orderNo);
        OrderNoTxt.setText(order);
        conn = mysqlconnect.ConnectDb();
        ErrorLbl.setVisible(false);
        Add1Err.setVisible(false);
        AddErr.setVisible(false);
        shipAddErr.setVisible(false);
        shipAdd1Err.setVisible(false);
        PostcodeErr.setVisible(false);
        TownErr.setVisible(false);
        centerErr.setVisible(false);
        emailErr.setVisible(false);
        firstnameErr.setVisible(false);
        phoneErr.setVisible(false);
        qtyErr.setVisible(false);
        surnameErr.setVisible(false);
        titleErr.setVisible(false);
        shipAddLbl.setVisible(false);
        shipAdd1Lbl.setVisible(false);
        shipAddressTxt.setVisible(false);
        shipAddress1Txt.setVisible(false);

        //Get the Shedtype from the database.
        String sqlShedType = "select shedtype from shedtype";
        try{
            pst=conn.prepareStatement(sqlShedType);
            rs = pst.executeQuery();
            while(rs.next()){
                String shedtype = rs.getString("shedtype");
                ComboShedType.addItem(shedtype);
                }
        } catch(Exception e){

        }
        //Get Shed Name from the Database
        String sqlShedname = "select shedname from products ";
        try{
            pst=conn.prepareStatement(sqlShedname);
            rs = pst.executeQuery();
            while(rs.next()){
                String shedname = rs.getString("shedname");
                ComboShedName.addItem(shedname);
                }
        } catch(Exception e){

        }

         //Get Roof Type from the Database
         String sqlRoofType = "select rooftype from rooftype";
        try{
            pst=conn.prepareStatement(sqlRoofType);
            rs = pst.executeQuery();
            while(rs.next()){
                String rooftype = rs.getString("rooftype");
                ComboRoofType.addItem(rooftype);
                }
        } catch(Exception e){

        }
         //Get Extras from the database
         String sqlExtras = "select extraname from extras";
        try{
            pst=conn.prepareStatement(sqlExtras);
            rs = pst.executeQuery();
            while(rs.next()){
                String extras = rs.getString("extraname");
                ComboExtras.addItem(extras);
                }
        } catch(Exception e){

        }

         //Get GaredenCenters from the database
         String sqlCenter = "select CenterName from centerlogindetails";
        try{
            pst=conn.prepareStatement(sqlCenter);
            rs = pst.executeQuery();
            while(rs.next()){
                String center = rs.getString("CenterName");
                ComboGardenCenter.addItem(center);
                }
        } catch(Exception e){

        }

    }//GEN-LAST:event_formWindowOpened

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        titleGrpRdBtn.clearSelection();
        AddressTxt.setText(null);
        Address1Txt.setText(null);
        ComboExtras.setSelectedIndex(0);
        ComboShedName.setSelectedIndex(0);
        ComboRoofType.setSelectedIndex(0);
        ComboShedType.setSelectedIndex(0);
        DepositTxt.setText(null);
        Emailtxt.setText(null);
        FirstnameTxt.setText(null);
        OrderNoTxt.setText(null);
        PhoneTxt.setText(null);
        PostcodeTxt.setText(null);
        QtyTxt.setText(null);
        SurnameTxt.setText(null);
        TownTxt.setText(null);
        UnitPriceTxt.setText(null);
        shipAddress1Txt.setText(null);
        shipAddressTxt.setText(null);
        subtotalTxt.setText(null);
    }//GEN-LAST:event_resetBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
         //Check that fields are not empty.
       if(ValidateSurname() && ValidateFirstname() && ValidateAddress() && ValidateAddress1() && ValidateTown()
                && ValidatePostcode() && ValidatePhone() && ValidateEmail() && ValidateShedType() && ValidateShedName()
                && ValidateRooftype() && ValidateExtras() && ValidateQty() && ValidateCenter())
        {
         // Fields have been checked not to be empty. Therefore the form details can be iserted into the database.
        String sql = "insert into tgscustomerform (orderid,Title,Firstname,Surname,Address, Address1,shipadd, shipadd1,Town,Postcode,Phone,email,shedtype,shedname,rooftype,extras,quantity,unitprice,deposit,subtotal,gardencentername) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1, OrderNoTxt.getText());
            pst.setString(2, title);
            pst.setString(3, FirstnameTxt.getText());
            pst.setString(4, SurnameTxt.getText());
            pst.setString(5, AddressTxt.getText());
            pst.setString(6, Address1Txt.getText());
            pst.setString(7, shipAddressTxt.getText());
            pst.setString(8, shipAddress1Txt.getText());
            pst.setString(9, TownTxt.getText());
            pst.setString(10, PostcodeTxt.getText());
            pst.setString(11, PhoneTxt.getText());
            pst.setString(12, Emailtxt.getText());
            String shedType = ComboShedType.getSelectedItem().toString();
            pst.setString(13, shedType);
            String prodName = ComboShedName.getSelectedItem().toString();
            pst.setString(14, prodName);
            String roofType = ComboRoofType.getSelectedItem().toString();
            pst.setString(15, roofType);
            String extras = ComboExtras.getSelectedItem().toString();
            pst.setString(16, extras);
            pst.setString(17, QtyTxt.getText());
            pst.setString(18, UnitPriceTxt.getText());
            pst.setString(19, DepositTxt.getText());
            pst.setString(20, subtotalTxt.getText());
            String garden = ComboGardenCenter.getSelectedItem().toString();
            pst.setString(21, garden);
            pst.execute();

            JOptionPane.showMessageDialog(null, "Order has been submitted to TGS HQ. Thank You.");
            close();
            System.out.println(garden);
            CenterHomeFrame home = new CenterHomeFrame();
            home.setVisible(true);

        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"All Fields are required.\nPlease Check for the following errors:\n Quantity must be numbers.");
        }

       } 
         //else{
          //   JOptionPane.showMessageDialog(null,"Select garden center.");
       //  }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void shipAddCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shipAddCheckActionPerformed
        // TODO add your handling code here:
        if(shipAddCheck.isSelected() == true){
            shipAddressTxt.setVisible(true);
            shipAddress1Txt.setVisible(true);
            shipAddLbl.setVisible(true);
            shipAdd1Lbl.setVisible(true);
        } else{
            shipAddressTxt.setVisible(false);
            shipAddress1Txt.setVisible(false);
            shipAddLbl.setVisible(false);
            shipAdd1Lbl.setVisible(false);
        }
    }//GEN-LAST:event_shipAddCheckActionPerformed

    private void RdBtnMrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdBtnMrActionPerformed
        // TODO add your handling code here:
        title = "Mr";
    }//GEN-LAST:event_RdBtnMrActionPerformed

    private void RdBtnMrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdBtnMrsActionPerformed
        // TODO add your handling code here:
        title = "Mrs";
    }//GEN-LAST:event_RdBtnMrsActionPerformed

    private void RdBtnMissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdBtnMissActionPerformed
        // TODO add your handling code here:
        title = "Miss";
    }//GEN-LAST:event_RdBtnMissActionPerformed

    private void RdBtnSirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdBtnSirActionPerformed
        // TODO add your handling code here:
        title = "Sir";
    }//GEN-LAST:event_RdBtnSirActionPerformed

    private void RdBtnMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdBtnMaActionPerformed
        // TODO add your handling code here:
        title = "Ma";
    }//GEN-LAST:event_RdBtnMaActionPerformed

    private void RdBtnDrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdBtnDrActionPerformed
        // TODO add your handling code here:
        title = "Dr";
    }//GEN-LAST:event_RdBtnDrActionPerformed

    private void ComboShedNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboShedNameActionPerformed
        // TODO add your handling code here:
        String shedname = ComboShedName.getSelectedItem().toString();
        try{
            String sql = "select prodimage,shedprice from products where shedname = '"+shedname+"'";
            pst = conn.prepareStatement(sql);
            //pst.setString(1, shedname);
            rs = pst.executeQuery();
            if(rs.next()){
               byte[] imagedata = rs.getBytes("prodimage");
               image = new ImageIcon(imagedata);
               ImageBox.setIcon(image);
               String setPrice = rs.getString("shedprice");
               shedPriceTxt.setText(setPrice);
            }

        } catch(Exception e){

        }
}//GEN-LAST:event_ComboShedNameActionPerformed

    private void ComboRoofTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboRoofTypeActionPerformed
        // On select of item, get price and set Roof type textfield to that price
        try{
            String roofname = ComboRoofType.getSelectedItem().toString();
            String sql = "select roofprice from rooftype where rooftype = '"+roofname+"'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            if(rs.next()){
                String setPrice = rs.getString("roofprice");
                roofPriceTxt.setText(setPrice);
            }

        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_ComboRoofTypeActionPerformed

    private void ComboExtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboExtrasActionPerformed
         // On select of item, get price and set Extra textfield to that price
       try{
            String extraname = ComboExtras.getSelectedItem().toString();
            String sql = "select extraprice from extras where extraname = '"+extraname+"'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            if(rs.next()){
                String setPrice = rs.getString("extraprice");
                extraPriceTxt.setText(setPrice);
            }

        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_ComboExtrasActionPerformed

        //RoundUp Values for unit price Amount
    public static double Round(double Rval, int Rpl) {
        double p = (double)Math.pow(10,Rpl);
        Rval = Rval * p;
        double tmp = Math.round(Rval);
        return (double)tmp/p;
  }
        //RoundUp Values for Subtotal Amount
     public static double Round1(double Rval, int Rpl) {
        double p = (double)Math.pow(10,Rpl);
        Rval = Rval * p;
        double tmp = Math.round(Rval);
        return (double)tmp/p;
  }
        //RoundUp Values for Deposit Amount
      public static double Round2(double Rval, int Rpl) {
        double p = (double)Math.pow(10,Rpl);
        Rval = Rval * p;
        double tmp = Math.round(Rval);
        return (double)tmp/p;
  }


    private void QtyTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QtyTxtKeyReleased
        //Perform Calculations on input of number in Quantity text field
        double qty = Float.valueOf(QtyTxt.getText());
        double shedPrice = Float.valueOf(shedPriceTxt.getText());
        double roofPrice = Float.valueOf(roofPriceTxt.getText());
        double extraPrice = Float.valueOf(extraPriceTxt.getText());
        double unitPrice = (shedPrice + roofPrice + extraPrice) * qty;
        //call method to round up unit price
        double roundUnitPrice = Round(unitPrice,2);
        String unitPrice1 = String.valueOf(roundUnitPrice);
        UnitPriceTxt.setText(unitPrice1);
        double deposit = 0.1 * unitPrice;
        double subtotal = unitPrice - deposit;
        //call method to round up subtotal amount
        double roundSubtotal = Round1(subtotal,2);
        String subtotal1 = String.valueOf(roundSubtotal);
        String subprice = String.valueOf(subtotal1);
        subtotalTxt.setText(subprice);
        //call method to round up Deposit Amount
        double roundDeposit = Round2(deposit,2);
        String depprice = String.valueOf(roundDeposit);
        DepositTxt.setText(depprice);
        
    }//GEN-LAST:event_QtyTxtKeyReleased

    private void PostcodeTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PostcodeTxtFocusLost
        // TODO add your handling code here:
        //Get Postcode to validate
        String check = PostcodeTxt.getText();
        String regexp="^([A-PR-UWYZ](([0-9](([0-9]|[A-HJKSTUW])?)?)|([A-HK-Y][0-9]([0-9]|[ABEHMNPRVWXY])?)) [0-9][ABD-HJLNP-UW-Z]{2})|GIR 0AA$";

        Pattern pattern = Pattern.compile(regexp);

        Matcher matcher = pattern.matcher(check.toUpperCase());

        if (matcher.matches()) {

            }
        else {
                JOptionPane.showMessageDialog(null, "Please input a valid UK Postcode.");
                PostcodeTxt.requestFocusInWindow();
                PostcodeErr.setVisible(true);
            }
    }//GEN-LAST:event_PostcodeTxtFocusLost

    private void PhoneTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PhoneTxtFocusLost
        // TODO add your handling code here:
        String check = PhoneTxt.getText();
        int phonecheck = PhoneTxt.getText().length();
        Pattern pattern = Pattern.compile("\\d{3}-\\d{8}");
        Matcher matcher = pattern.matcher(check);
        if (matcher.matches() && phonecheck == 12) {
            phoneErr.setVisible(false);
    	  }
        else
        {
    	  JOptionPane.showMessageDialog(null,"Phone Number must be 12 digits with '-' in the format XXX-XXXXXXX .");
          PhoneTxt.requestFocusInWindow();
          phoneErr.setVisible(true);
         }
    }//GEN-LAST:event_PhoneTxtFocusLost

    private void EmailtxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailtxtFocusLost
         //Get the string for validation
      String email = Emailtxt.getText();

      //Set the email pattern string
      Pattern p = Pattern.compile(".+@.+\\.[a-z]+");

      //Match the given string with the pattern
      Matcher m = p.matcher(email);

      //check whether match is found
      boolean matchFound = m.matches();
      if (matchFound){

      }
      else{
        JOptionPane.showMessageDialog(null, "Please input a valid email address.");
        Emailtxt.requestFocusInWindow();
        emailErr.setVisible(true);
      }
    }//GEN-LAST:event_EmailtxtFocusLost

    private void ComboGardenCenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboGardenCenterActionPerformed
        // TODO add your handling code here:
                    
    }//GEN-LAST:event_ComboGardenCenterActionPerformed

     public boolean ValidateSurname(){
        boolean check = false;
        String name = SurnameTxt.getText();
        if(name == null || name.length() == 0){
            JOptionPane.showMessageDialog(null, "Surname cannot be empty.");
            SurnameTxt.requestFocusInWindow();
            surnameErr.setVisible(true);
        }
        else{
            check = true;
            surnameErr.setVisible(false);
        }
    return check;
      }


    public boolean ValidateFirstname(){
        boolean check = false;
        String name = FirstnameTxt.getText();
        if(name.length() == 0 || name == null){
            JOptionPane.showMessageDialog(null, "Firstname cannot be empty.");
            FirstnameTxt.requestFocusInWindow();
            firstnameErr.setVisible(true);
        } else{
            check = true;
            firstnameErr.setVisible(false);
        }
        return check;
      }

    public boolean ValidateAddress(){
        boolean check = false;
        String name = AddressTxt.getText();
        if(name.length() == 0 || name == null){
            JOptionPane.showMessageDialog(null, "Address 1 cannot be empty.");
            AddressTxt.requestFocusInWindow();
            AddErr.setVisible(true);
        }else{
            check = true;
            AddErr.setVisible(false);
        }
        return check;
      }

    public boolean ValidateAddress1(){
        boolean check = false;
        String name = Address1Txt.getText();
        if(name.length() == 0 || name == null){
            JOptionPane.showMessageDialog(null, "Address 2 cannot be empty.");
            Address1Txt.requestFocusInWindow();
            Add1Err.setVisible(true);
        } else{
            check = true;
            Add1Err.setVisible(false);
        }
        return check;
      }

//    public boolean ValidateShippingAddress(){
//        boolean check = false;
//        String add = shipAddressTxt.getText();
//        String add1 = shipAddress1Txt.getText();
//        if(shipAddCheck.isSelected()){
//            if(add.length() == 0 || add == null){
//            JOptionPane.showMessageDialog(null, "Shipping Address 1 cannot be empty.");
//            shipAddressTxt.requestFocusInWindow();
//            shipAddErr.setVisible(true);
//          }
//        if(add1.length() == 0 || add1 == null){
//            JOptionPane.showMessageDialog(null, "Shipping Address 2 cannot be empty.");
//            shipAddress1Txt.requestFocusInWindow();
//            shipAdd1Err.setVisible(true);
//         }
//        }
//      }

    public boolean ValidateTown(){
        boolean check = false;
        String name = TownTxt.getText();
        if(name.length() == 0 || name == null){
            JOptionPane.showMessageDialog(null, "Town cannot be empty.");
            TownTxt.requestFocusInWindow();
            TownErr.setVisible(true);
        } else{
            check = true;
            TownErr.setVisible(false);
        }
        return check;
      }

    public boolean ValidatePhone(){
        boolean check = false;
        String name = PhoneTxt.getText();
        if(name.length() == 0 || name == null){
            JOptionPane.showMessageDialog(null, "Telephone cannot be empty.");
            PhoneTxt.requestFocusInWindow();
            phoneErr.setVisible(true);
        } else{
            check = true;
            phoneErr.setVisible(false);
        }
        return check;
      }

    public boolean ValidateQty(){
        boolean check = false;
        String name = QtyTxt.getText();
        int qty = Integer.valueOf(name);
        if(name.length() == 0 || name == null || qty == 0){
            JOptionPane.showMessageDialog(null, "Quantity cannot be empty or 0.");
            QtyTxt.requestFocusInWindow();
            qtyErr.setVisible(true);
        } else{
                 check = true;
        }
    return check;

      }

    public boolean ValidatePostcode(){
        boolean check = false;
        String name = PostcodeTxt.getText();
        if(name == null || name.length() == 0){
            JOptionPane.showMessageDialog(null, "Postcode cannot be empty.");
            PostcodeTxt.requestFocusInWindow();
            PostcodeErr.setVisible(true);
        } else{
            check = true;
            PostcodeErr.setVisible(false);
        }
        return check;
      }

    public boolean ValidateEmail(){
        boolean check = false;
        String name = Emailtxt.getText();
        if(name.length() == 0 || name == null){
            JOptionPane.showMessageDialog(null, "Email cannot be empty.");
            Emailtxt.requestFocusInWindow();
            emailErr.setVisible(true);
        } else{
            check = true;
            emailErr.setVisible(false);
        }
        return check;
      }


     public boolean ValidateShedType(){
         boolean check = false;
        int val = ComboShedType.getSelectedIndex();
        if(val == 0){
            JOptionPane.showMessageDialog(null, "Please select a Shed Type.");
            ComboShedType.requestFocusInWindow();
        } else{
            check = true;
        }
        return check;
    }

    public boolean ValidateShedName(){
        boolean check = false;
        int val = ComboShedName.getSelectedIndex();
        if(val == 0){
            JOptionPane.showMessageDialog(null, "Please select a Shed Name.");
            ComboShedName.requestFocusInWindow();
        } else{
            check = true;
        }
        return check;
    }

    public boolean ValidateRooftype(){
        boolean check = false;
        int val = ComboRoofType.getSelectedIndex();
        if(val == 0){
            JOptionPane.showMessageDialog(null, "Please select a Shed Roof.");
            ComboRoofType.requestFocusInWindow();
        } else{
            check = true;
        }
        return check;
    }

    public boolean ValidateExtras(){
        boolean check = false;
        int val = ComboExtras.getSelectedIndex();
        if(val == 0){
            JOptionPane.showMessageDialog(null, "Please select any or no extras as requested.");
            ComboExtras.requestFocusInWindow();
        } else{
            check = true;
        }
        return check;
    }

    
      public boolean ValidateCenter(){
        boolean check = false;
        int val = ComboGardenCenter.getSelectedIndex();
        if(val == 0){
            JOptionPane.showMessageDialog(null, "Please select a Garden Center.");
            ComboGardenCenter.requestFocusInWindow();
        } else{
            check = true;
        }
        return check;
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CenterOrderForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add1Err;
    private javax.swing.JLabel AddErr;
    private javax.swing.JTextField Address1Txt;
    private javax.swing.JTextField AddressTxt;
    private javax.swing.JButton BackBtn;
    private javax.swing.JComboBox ComboExtras;
    private javax.swing.JComboBox ComboGardenCenter;
    private javax.swing.JComboBox ComboRoofType;
    private javax.swing.JComboBox ComboShedName;
    private javax.swing.JComboBox ComboShedType;
    private javax.swing.JPanel CustOrderPanel;
    private javax.swing.JScrollPane CustOrderScrollPane;
    private javax.swing.JTextField DepositTxt;
    private javax.swing.JTextField Emailtxt;
    private javax.swing.JLabel ErrorLbl;
    private javax.swing.JTextField FirstnameTxt;
    private javax.swing.JLabel ImageBox;
    private javax.swing.JButton LogOutBtn;
    private javax.swing.JTextField OrderNoTxt;
    private javax.swing.JTextField PhoneTxt;
    private javax.swing.JLabel PostcodeErr;
    private javax.swing.JTextField PostcodeTxt;
    private javax.swing.JTextField QtyTxt;
    private javax.swing.JRadioButton RdBtnDr;
    private javax.swing.JRadioButton RdBtnMa;
    private javax.swing.JRadioButton RdBtnMiss;
    private javax.swing.JRadioButton RdBtnMr;
    private javax.swing.JRadioButton RdBtnMrs;
    private javax.swing.JRadioButton RdBtnSir;
    private javax.swing.JTextField SurnameTxt;
    private javax.swing.JLabel TownErr;
    private javax.swing.JTextField TownTxt;
    private javax.swing.JTextField UnitPriceTxt;
    private javax.swing.JLabel centerErr;
    private javax.swing.JLabel emailErr;
    private javax.swing.JTextField extraPriceTxt;
    private javax.swing.JLabel firstnameErr;
    private javax.swing.JDesktopPane imgBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel phoneErr;
    private javax.swing.JLabel qtyErr;
    private javax.swing.JButton resetBtn;
    private javax.swing.JTextField roofPriceTxt;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField shedPriceTxt;
    private javax.swing.JLabel shipAdd1Err;
    private javax.swing.JLabel shipAdd1Lbl;
    private javax.swing.JCheckBox shipAddCheck;
    private javax.swing.JLabel shipAddErr;
    private javax.swing.JLabel shipAddLbl;
    private javax.swing.JTextField shipAddress1Txt;
    private javax.swing.JTextField shipAddressTxt;
    private javax.swing.JTextField subtotalTxt;
    private javax.swing.JLabel surnameErr;
    private javax.swing.JLabel titleErr;
    private javax.swing.ButtonGroup titleGrpRdBtn;
    // End of variables declaration//GEN-END:variables

    private String title;
    private ImageIcon image = null;
    int price = 0;
    double shedprice = 0;
    double extraprice = 0;
    double roofprice = 0;
}
